(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.img_1 = function() {
	this.initialize(img.img_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,720,616);


(lib.img_2 = function() {
	this.initialize(img.img_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1940,500);


(lib.img_3 = function() {
	this.initialize(img.img_3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2160,394);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.image1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.instance = new lib.img_1();
	this.instance.setTransform(52,2,0.1564,0.1564);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F7F8F3").s().p("AzbEcIAAo3MAm2AAAIAAI3g");
	this.shape.setTransform(-72.2,28.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image1, new cjs.Rectangle(-196.5,0,361.1,98.4), null);


(lib.Image_3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.img_3();
	this.instance.setTransform(-67,-10,0.1797,0.1797);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Image_3, new cjs.Rectangle(-67,-10,388.2,70.8), null);


(lib.Image_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.instance = new lib.img_2();
	this.instance.setTransform(72,-11,0.1301,0.1301);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AAD7F4").s().p("AnzEOIAAobIPnAAIAAIbg");
	this.shape.setTransform(21.975,22.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Image_2, new cjs.Rectangle(-28,-11,352.4,65.1), null);


(lib.Color_3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#152B52").s().p("A3bXcMAAAgu3MAu3AAAMAAAAu3g");
	this.shape.setTransform(149.9998,150,1.0001,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Color_3, new cjs.Rectangle(0,0,300,300), null);


(lib.Color_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0870B9").s().p("A3bXcMAAAgu3MAu3AAAMAAAAu3g");
	this.shape.setTransform(149.9998,150,1.0001,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Color_2, new cjs.Rectangle(0,0,300,300), null);


(lib.Color_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00919D").s().p("A3bXcMAAAgu3MAu3AAAMAAAAu3g");
	this.shape.setTransform(149.9998,150,1.0001,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Color_1, new cjs.Rectangle(0,0,300,300), null);


(lib.Callout_Body = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgCADQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIACgCQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACACQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAgBg");
	this.shape.setTransform(-28.325,-168.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMAQQgGgGAAgKQAAgIAFgGQAGgGAHAAQAKAAAFAIQAEAFAAAIIgeAAQAAAGAEAEQAEAEAEAAQAFAAADgDQADgCABgDIAGADIgGAGQgFAFgHAAQgIAAgFgFgAAMgDQgBgFgDgDQgEgDgEAAQgDAAgEADQgCADgBAFIAWAAIAAAAg");
	this.shape_1.setTransform(-31.65,-169.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgNALIAGgDQACAHAFAAQABAAABAAQAAgBABAAQAAAAABAAQAAgBABAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBIgFgCQgGgCgCgDQgCgCAAgEQAAgFADgDQADgDAEAAQAIAAADAHIgGADQgBgEgEAAQgEAAAAAFQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAIAEACQAHAEACACQADACAAAEQAAAGgEAEQgEADgGAAQgJAAgEgKg");
	this.shape_2.setTransform(-35.525,-169.675);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgNAQQgGgGAAgKQAAgJAGgFQAFgGAIAAQAIAAAFAHIAAgGIAHAAIAAAnIgHAAIAAgGQgFAHgIAAQgIAAgFgFgAgIgKQgEAEAAAGQAAAGAEAFQADAEAFAAQAGAAAEgFQADgEAAgGQAAgGgEgEQgEgEgFAAQgEAAgEAEg");
	this.shape_3.setTransform(-39.825,-169.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAJAjIAAgZQAAgEgCgDQgCgDgFAAQgDAAgDADQgCAEAAAHIAAAVIgHAAIAAhFIAHAAIAAAiQAEgFAGAAQAIAAAEAFQACADAAAHIAAAZg");
	this.shape_4.setTransform(-44.4,-171.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgKAPQgGgGAAgJQAAgIAGgGQAGgGAIAAQAHAAAGAEIAAAIQgFgGgIAAQgFAAgDAEQgFAEAAAGQAAAHAFAEQAEAEAEAAQAIAAAFgGIAAAIQgGAEgHAAQgIAAgGgGg");
	this.shape_5.setTransform(-48.725,-169.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgKAUIAAgmIAHAAIAAAEQADgFAFAAIAGABIgEAHIgDgCQgEAAgBADQgCADAAAHIAAAUg");
	this.shape_6.setTransform(-51.85,-169.725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgLAPQgEgEAAgHIAAgXIAHAAIAAAWQAAAGACACQACADAEAAQAEAAADgDQACgCAAgGIAAgWIAHAAIAAAXQAAAHgEAEQgFAFgHAAQgGAAgFgFg");
	this.shape_7.setTransform(-55.775,-169.625);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgTAfIAAg8IAHAAIAAAFQAFgGAIAAQAIAAAGAGQAFAGAAAJQAAAIgFAFQgFAGgJAAQgIAAgFgGIAAAbgAgIgUQgEAEAAAHQAAAGADADQAEAEAFAAQAGAAADgEQAEgDAAgGQAAgHgEgEQgEgEgFAAQgEAAgEAEg");
	this.shape_8.setTransform(-60.375,-168.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgMAQQgGgGAAgKQAAgIAFgGQAFgGAIAAQAKAAAFAIQAEAFAAAIIgeAAQAAAGAEAEQADAEAFAAQAEAAAEgDQACgCACgDIAGADIgGAGQgFAFgHAAQgIAAgFgFgAAMgDQgBgFgEgDQgDgDgEAAQgDAAgDADQgDADgCAFIAXAAIAAAAg");
	this.shape_9.setTransform(-67.4,-169.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgKAUIAAgmIAHAAIAAAEQADgFAFAAIAGABIgEAHIgDgCQgEAAgBADQgCADAAAHIAAAUg");
	this.shape_10.setTransform(-70.75,-169.725);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgOAPQgGgGAAgJQAAgIAGgGQAGgGAIAAQAJAAAGAGQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGgAgJgKQgEAEAAAGQAAAHAEAEQAEAEAFAAQAFAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgFAAQgFAAgEAEg");
	this.shape_11.setTransform(-75,-169.675);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgEAbIAAggIgEAAIAAgGIAEAAIAAgPIAGAAIAAAPIAHAAIAAAGIgHAAIAAAgg");
	this.shape_12.setTransform(-78.35,-170.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgNALIAGgDQACAHAFAAQABAAABAAQAAgBABAAQAAAAABAAQAAgBABAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBIgFgCQgGgCgCgDQgCgCAAgEQAAgFADgDQADgDAEAAQAIAAADAHIgGADQgBgEgEAAQgEAAAAAFQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAIAEACQAHAEACACQADACAAAEQAAAGgEAEQgEADgGAAQgJAAgEgKg");
	this.shape_13.setTransform(-81.075,-169.675);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgJAEIAAgHIATAAIAAAHg");
	this.shape_14.setTransform(-33.7,-179.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AAJAUIAAgXQAAgFgCgCQgCgDgFAAQgDAAgDADQgCADAAAHIAAAUIgHAAIAAgmIAHAAIAAAEQAEgFAGAAQAIAAADAFQADAEAAAHIAAAXg");
	this.shape_15.setTransform(-37.4,-179.675);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgCAeIAAgnIAGAAIAAAngAgCgUQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABIABADIgBAEQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAAAg");
	this.shape_16.setTransform(-40.625,-180.625);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgEAbIAAggIgEAAIAAgHIAEAAIAAgOIAGAAIAAAOIAHAAIAAAHIgHAAIAAAgg");
	this.shape_17.setTransform(-44.65,-180.35);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAMAUIgMgQIgMAQIgIAAIARgUIgOgTIAIAAIAKAOIAKgOIAIAAIgPATIARAUg");
	this.shape_18.setTransform(-47.95,-179.625);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgMAQQgGgGAAgKQAAgIAFgGQAGgGAHAAQAKAAAFAIQAEAFAAAIIgeAAQAAAGAEAEQAEAEAEAAQAFAAADgDQADgCABgDIAGADIgGAGQgFAFgHAAQgIAAgFgFgAAMgDQgBgFgDgDQgEgDgEAAQgDAAgEADQgCADgBAFIAWAAIAAAAg");
	this.shape_19.setTransform(-52.35,-179.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AAJAUIAAgXQAAgFgCgCQgCgDgEAAQgEAAgDADQgCADAAAHIAAAUIgHAAIAAgmIAHAAIAAAEQAEgFAGAAQAIAAADAFQADAEAAAHIAAAXg");
	this.shape_20.setTransform(-56.85,-179.675);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgKAUIAAgmIAHAAIAAAEQADgFAFAAIAGABIgEAHIgDgCQgEAAgBADQgCADAAAHIAAAUg");
	this.shape_21.setTransform(-62.3,-179.675);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgLAPQgEgEAAgHIAAgXIAHAAIAAAWQAAAGACACQACADAEAAQAEAAADgDQACgCAAgGIAAgWIAHAAIAAAXQAAAHgEAEQgFAFgHAAQgGAAgFgFg");
	this.shape_22.setTransform(-66.275,-179.575);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgOAPQgGgGAAgJQAAgIAGgGQAGgGAIAAQAJAAAGAGQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGgAgJgKQgEAEAAAGQAAAHAEAEQAEAEAFAAQAFAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgFAAQgFAAgEAEg");
	this.shape_23.setTransform(-70.95,-179.625);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgOAfIAMgaIgSgjIAIAAIANAdIANgdIAHAAIgcA9g");
	this.shape_24.setTransform(-75.675,-178.525);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgGAjIAAghIgDAAIAAgFIADAAIAAgRQAAgIAFgEQACgCAEAAIAFABIAAAGIgFgBQAAAAgBAAQgBABAAAAQgBAAAAABQAAAAgBABIAAAFIAAARIAJAAIAAAFIgJAAIAAAhg");
	this.shape_25.setTransform(-25.8,-191.175);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgGAjIAAghIgDAAIAAgFIADAAIAAgRQAAgIAFgEQACgCAEAAIAFABIAAAGIgFgBQAAAAgBAAQgBABAAAAQgBAAAAABQAAAAgBABIAAAFIAAARIAJAAIAAAFIgJAAIAAAhg");
	this.shape_26.setTransform(-28.05,-191.175);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgOAPQgGgGAAgJQAAgIAGgGQAGgGAIAAQAJAAAGAGQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGgAgJgKQgEAEAAAGQAAAHAEAEQAEAEAFAAQAFAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgFAAQgFAAgEAEg");
	this.shape_27.setTransform(-31.8,-189.625);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgPAbQgDgCgCgEIAFgEIAEAFQAFAEAGAAQAFAAAFgFQAEgFAAgGQAAgHgEgEQgFgEgFAAQgGAAgHAEIAKgeIAYAAIAAAGIgVAAIgDAOIADAAQAKAAAGAGQAFAFAAAKQAAAKgHAGQgGAGgJAAQgIAAgGgFg");
	this.shape_28.setTransform(-39.425,-190.775);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgBApIAAgJQgHAAgFgEQgEgFgCgHIAHgCQABAFADADQADAEAEAAIAAgaQgHgCgDgDQgFgFAAgFQAAgIAFgEQAEgEAGgBIAAgIIAFAAIAAAIQAEAAADADQAEADACAEIgFADQgCgDgCgBQgBgBAAAAQAAAAgBgBQAAAAgBAAQgBAAAAAAIAAAVQAHADAEADQAFAEAAAHQAAAHgEAFQgFAGgHABIAAAJgAAEAZQAEAAACgEQACgEAAgEQAAgEgDgDIgFgDgAgHgWQgCADAAAEQAAADADACIAFAEIAAgTQgEAAgCADg");
	this.shape_29.setTransform(-44.525,-190.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgMAQQgGgGAAgKQAAgIAFgGQAFgGAIAAQAKAAAFAIQAEAFAAAIIgeAAQAAAGAEAEQAEAEADAAQAFAAADgDQADgCACgDIAFADIgEAGQgGAFgIAAQgGAAgGgFgAAMgDQgBgFgDgDQgDgDgFAAQgDAAgEADQgCADgBAFIAWAAIAAAAg");
	this.shape_30.setTransform(-51.7,-189.625);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgTgUIAIAAIALAaIAMgaIAHAAIgTApg");
	this.shape_31.setTransform(-56,-189.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgCAeIAAgnIAGAAIAAAngAgCgUQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABIABADIgBAEQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAAAg");
	this.shape_32.setTransform(-58.975,-190.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgMAQQgGgGAAgKQAAgIAFgGQAGgGAHAAQAKAAAFAIQAEAFAAAIIgeAAQAAAGAEAEQADAEAEAAQAGAAACgDQAEgCABgDIAFADIgEAGQgGAFgIAAQgGAAgGgFgAAMgDQgBgFgEgDQgDgDgEAAQgDAAgDADQgEADgBAFIAXAAIAAAAg");
	this.shape_33.setTransform(-62.2,-189.625);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgKAPQgGgGAAgJQAAgIAGgGQAGgGAIAAQAHAAAGAEIAAAIQgFgGgIAAQgFAAgDAEQgFAEAAAGQAAAHAFAEQAEAEAEAAQAIAAAFgGIAAAIQgGAEgHAAQgIAAgGgGg");
	this.shape_34.setTransform(-66.575,-189.625);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgMAQQgGgGAAgKQAAgIAFgGQAGgGAHAAQAKAAAFAIQAEAFAAAIIgeAAQAAAGAEAEQAEAEAEAAQAEAAAEgDQADgCABgDIAGADIgGAGQgFAFgHAAQgIAAgFgFgAAMgDQgBgFgDgDQgDgDgFAAQgDAAgDADQgDADgCAFIAXAAIAAAAg");
	this.shape_35.setTransform(-70.9,-189.625);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgKAUIAAgmIAHAAIAAAEQADgFAFAAIAGABIgEAHIgDgCQgEAAgBADQgCADAAAHIAAAUg");
	this.shape_36.setTransform(-74.25,-189.675);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgOAPQgGgGAAgJQAAgIAGgGQAGgGAIAAQAJAAAGAGQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGgAgJgKQgEAEAAAGQAAAHAEAEQAEAEAFAAQAFAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgFAAQgFAAgEAEg");
	this.shape_37.setTransform(-80.65,-189.625);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgEAbIAAggIgEAAIAAgHIAEAAIAAgOIAGAAIAAAOIAHAAIAAAHIgHAAIAAAgg");
	this.shape_38.setTransform(-84,-190.35);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgNAeQgGgGAAgKQAAgJAGgFQAFgFAIAAQAIAAAFAFIAAgiIAHAAIAABEIgHAAIAAgFQgFAGgIAAQgIAAgFgFgAgIAEQgEAEAAAGQAAAHAEAEQADAEAFAAQAGAAAEgEQADgEAAgGQAAgIgEgEQgEgDgFAAQgEAAgEAEg");
	this.shape_39.setTransform(-29.375,-201.025);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgNAQQgGgGAAgKQAAgJAGgFQAFgGAIAAQAIAAAFAHIAAgGIAHAAIAAAnIgHAAIAAgGQgFAHgIAAQgIAAgFgFgAgIgKQgEAEAAAGQAAAGAEAFQADAEAFAAQAGAAAEgFQADgEAAgGQAAgGgEgEQgEgEgFAAQgEAAgEAEg");
	this.shape_40.setTransform(-34.375,-199.575);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgNALIAGgDQACAHAFAAQABAAABAAQAAAAABgBQAAAAABAAQAAgBABAAQAAgBABAAQAAAAAAgBQABgBAAAAQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBIgFgCQgGgCgCgDQgCgCAAgEQAAgFADgDQADgDAEAAQAIAAADAHIgGADQgBgEgEAAQgEAAAAAFQAAAAAAABQAAAAABABQAAAAAAAAQAAABABAAIAEACQAHAEACACQADACAAAEQAAAGgEAEQgEADgGAAQgJAAgEgKg");
	this.shape_41.setTransform(-40.475,-199.575);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgCAeIAAgnIAGAAIAAAngAgCgUQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABIABADIgBAEQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAAAg");
	this.shape_42.setTransform(-43.225,-200.575);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAJAjIAAgZQAAgEgCgDQgCgDgEAAQgEAAgCADQgDAEAAAHIAAAVIgHAAIAAhFIAHAAIAAAiQAEgFAGAAQAIAAADAFQADADAAAHIAAAZg");
	this.shape_43.setTransform(-46.35,-201.075);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgEAbIAAggIgEAAIAAgGIAEAAIAAgPIAGAAIAAAPIAHAAIAAAGIgHAAIAAAgg");
	this.shape_44.setTransform(-49.45,-200.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AAJAUIAAgXQAAgFgCgCQgCgDgFAAQgDAAgCADQgDADAAAHIAAAUIgHAAIAAgmIAHAAIAAAEQAEgFAGAAQAIAAAEAFQACAEAAAHIAAAXg");
	this.shape_45.setTransform(-55,-199.625);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgOAPQgGgGAAgJQAAgIAGgGQAGgGAIAAQAJAAAGAGQAGAGAAAIQAAAJgGAGQgGAGgJAAQgIAAgGgGgAgJgKQgEAEAAAGQAAAHAEAEQAEAEAFAAQAFAAAEgEQAFgEAAgHQAAgGgFgEQgEgEgFAAQgFAAgEAEg");
	this.shape_46.setTransform(-59.7,-199.575);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgCAeIAAgnIAGAAIAAAngAgCgUQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABIABADIgBAEQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQgBAAAAAAg");
	this.shape_47.setTransform(-63.175,-200.575);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgEAbIAAggIgEAAIAAgGIAEAAIAAgPIAGAAIAAAPIAHAAIAAAGIgHAAIAAAgg");
	this.shape_48.setTransform(-65.05,-200.3);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AAJAUIAAgXQAAgFgCgCQgCgDgFAAQgDAAgDADQgCADAAAHIAAAUIgHAAIAAgmIAHAAIAAAEQAEgFAGAAQAIAAAEAFQACAEAAAHIAAAXg");
	this.shape_49.setTransform(-68.35,-199.625);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgMAQQgGgGAAgKQAAgIAFgGQAFgGAIAAQAKAAAFAIQAEAFAAAIIgeAAQAAAGAEAEQAEAEADAAQAFAAADgDQADgCACgDIAFADIgEAGQgGAFgIAAQgGAAgGgFgAAMgDQgBgFgDgDQgDgDgFAAQgDAAgEADQgCADgBAFIAWAAIAAAAg");
	this.shape_50.setTransform(-72.85,-199.575);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgUgLIgHArIgHAAIALhCIAXA1IAZg1IAKBCIgHAAIgGgrIgWAug");
	this.shape_51.setTransform(-79.225,-200.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Callout_Body, new cjs.Rectangle(-87.7,-209.2,65.4,46.599999999999994), null);


(lib.Logo_Stacked = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(1));

	// Paper_Souce
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AqpCYIgIAAIgDgDQgFgDgHgCQgFgCgLACQgJABgGgDQgGgFAAgSQgBgMADgOQABgDgCgEQgBgKAIgGQADgCACABQAIAFACAFIgCAeQABAHAGAFQAKgBAQAEIAZAFQAMABALgDIAGAAQAkgJAJgWIACgLIAAgFQACgSgGgPIgFgEQgNgLgTgHIgHgBIgqgKQgZgGgNgIQgOgIgJgPQgNghAIgjQAKgZAVgRIAJgEIAGgEIAHgCIAHgDIAKgDIALgBQAHAAACgCIAKAAQAKgBAKABIAfAJIAEAAQAOADAJALQADAFgCAOIgCAUIgFAFQgQAAAAgJIgCgFIgBgEQgEgGgGgEIgDgBIgFgFQgNgFgMgCIgFABQgcgGgYARIgCAEIgFAEQgEAIgDAKIgGAOIgDAEQgBACABADQADAGAFAFQAKAKANAHIAdAMIAFAAIAPAEIAIABIALAEQADABAEAAIAFAFIAGADQADACALABQAJABADACQAJAGADAKIgBAIQgBAFACADIAHAIQAFAGACAEQACAEgCANIgDAQQgGAQgIANQgSAYgyAQIgIABIgJABIgQABQgKAAgKgCgAmNCYIgGAAIgOgDIgIgDIgFgBIgGgGQgDgFgCgBQgDgCgEABIgHAAIgKgEIgIgJIgFgDIgHgKIgFgEIgEgHIgKgOQgFgJgDgNIgFgKIgCgKIAAgGQgJgiAJglQAAgGACgDIAIgVIAFgOIAPgPIAKgHIAJgOIADgBIACgEIAHgEQAPgKAPgFQAKgEAWgFIAFAAIARgCQAigBAfALQAJACAGADQAHAGAFAPIAHAHIAKgCQAFgBAEABIAHAGQAJAJAGAKIABAFQAKAUAGAcIAAARQADASgEAQIgBAIQAAAFgBAEQgEAPgHARIgDAEIgKARIgGAGIgBACIgCABIgCAEIgRARIgCAAIgFAFIgEABIgDAEQgDABgGgBQgGAAgDABQgBABgDAGQgDAEgJAGIgDAAIgGADIgDAAQgUAGgVAAQgMAAgMgCgAmjh4QghASgMAjIgDAMIgFASQgBADABAEQACADgBACIgFAQIACADIAAAFIACAEQADAJADATIADALIACAKQAJAWALAQIAKAKIAAACIAIAGIADAEIACAAIAHAFIAFABIAFADQARAIAUgBIAKAAQAegIARgMQAQgNANgZQACgEACgIIADgMQAGgHABgDIABAAQABgDgCgEIgDgGQgBgNABgMQAAgTgDgRIgBgLQgGgYgQgTQgQgTgXgKQgLgDgRgEIgGAAIgRgCQgCABgHABIgDACIgDAAgAhuCVIgHAAIgDgCIgDAAIgEgEIgIgHQgIABgIgCQgKgFgJgPQgIgNgFgPIAAgOQgCgGAAgEQACgJgCgIIABgNQAAgGgBgHIAAgFQgBgHABgIIgBgLQABgHAAgJIgBgQIAAgKQABgKgBgIIgBgTQgBgEACgEIgBgQQgEgKgKgCIgJgBQgGgBgBgDQgCgBABgEIABgGIAGgEQAOgBAPADIAlgBIAdAAQAIAEAAAIIgDAEQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIgIABQgHABgFAFQgFAJgBALIAAAVIgBALQgBAEgFAGQgBAMACAPIgCAHIABAFQgBAIABAJIADAMIAEAKIAAALIAAAPIAEAiIAKAVIADAIQABAEADACQABAAAAAAQABABAAAAQABAAABgBQAAAAABAAIAFAAIASAGIAGAAIAYAAQALACAKgCIAJAAQALgDAJgEQASgLALgkQABgEABgIIABgNIAAhkQABgPgBgPQAAgEACgDQABgLgCgHQgDgJgJgFIgOgDQgHgCAAgKIAGgEIAJAAIAXABQARABAHgBIAIAAIAKAAIAOAAIADgBQAIgBAIABQADABAEgCQAEgBAHACIAVAAQACABAJgBQAaAEATATQAFAFADAEQAFALACAMIAAAJIABAEQAAAHgBAGIgCAIIgIAGQgGAEgBADQgCAEACADQACAEgBACQgBAGgDAEIgMAMIgOAGQgLAHgFACIgHAEQgEADAAAFIADAGIADACIADAGQACADAGAFIAoAtIAJAIIAJALIAGAGIAKAMQAPAHAIACIAEADIACAEIAAAHIgBAAQgCACgGgBIgJAAQgXABgVgBIgIgHQgFgEgCgDIgHgNIgBgGIgFgGIAAgBQgGgIgGgEIgKgEQgEgDgDgGIgFgDIgGgIIgDgCIgLgMIgDgEIgDgCIgFgHIgFgDIgFgHQgGgEgCgEQgDgHADgHIAKgIQAYgHAZgNIADgEQAEgCABgCQAIgLADgNQACgGAAgIQABgPgDgMQgHgXgmgQQgJgEgPAAQgQgBgHAFQgDADAAAEIAAAKIAAAMQABAIgBAEQgBADABAEIAAAKQgCATABAZQABAHgBAGIAAAVIAAAtQgBAEABAHIgFANQgBANAFAMIACAPQADAIASADQARADAAAKIgBACIgIAGQgWgBgTgFQgHAAgJACIgCACQgGAAgEgCIgGgCQgCgBgBgFIgBgGQgDgBgDABIgFADIgbANQgMAEgKACIgGAAQgMABgMAAQgSAAgTgEgAFwCXQgtgGgegWIgJgIQgGgFgGgGIgDgJIgHgGIgIgHQgFgHgBgGIgFgJQgEgIAAgHQgMgnAJgoIADgQIADgIQAIgHABgEIACgJIACgBIAEgJQABgFABgCQAGgEABgCIARgSIAIgEQAXgQAbgHIAOgDIAPgDIAFABIAFgBQAggCAkAJIAUAFIANAEQAIACADAFQAEAHgCAPIgGAYIgEADQgKAAgCgEIgDgJQgDgLgIgHQgdgTgsACQgsACgbAVIgFAIIgKAOIgDAHIgCACIgDAKIgIAWQgBAFgGAKIgBAEIgEAFQgCADAAADIAEAGIAEADIADADQABAGAAAMQACAMAFARIAFAHIAGAOIAHAJIAEAEIACAFQACADAGAEQAIAJALAHQATAJAWAGQAEABAJAAQAPAEAPgBQADgBAGABIAEgDIAFAAIAFgBIAIAAIAHgBIAGgHQALgKAPAAIADACQABAKgIAJQgHAHgLAEIgSAFQgcAKgeAAQgOAAgPgCgAKfCTIgPAAQgIAAgHgCIgSAAIgHgEIgJgCQgEgCgMAGIgKACIgPABQgKACgLgCQgNgCgDgGIAAgCQABgEAFgEIAIgGQAKgNAEgRIAAgJQACgUgCgVQgCgRADgSIAAgMQADgFABgDQABgFgDgJQgDgKAAgFIAAgeQACgRgDgPIgCgLQgBgGgDgCQgDgCgFgBIgKgBQgHAAgFgFQgBgIAHgGIAAABIAvAAIAtAAQAcgCATABQAGABAJgBIAKAAIAMAAQAAAAABAAQABABAAAAQABAAAAgBQABAAAAAAIAMAAIALACQAGACABADQAFAHgGAXIAAAFQABADgBACIgEAEIgEADIgLgBIgCgEIgFgNQgDgHgJAAQgDgCgKAAIgQgBQgagEgaAEIgHAAIgGABQgGAEgBAFQAEAIABAKIAAAJQABAHAAASQAAASACAIIAAAGQgBADABADQABAEAHADIALgBQASABAMgCIAXAAIAEgDQAKgEAAgGQACgDgBgIIACgGQAFgDADAAQAIAHACADQACAFgBAKIgBAOIAAA3IgEAFIgGABQgDAAgCgBQgDgDgBgEIgCgJQABgJgCgDQgFgJgQgDQgOgCgRACIgPAAQgJgBgDACQgDABgCAEQgCADAAAEIAAAGIAAALQgBAIABAFQABAFgCAPIgBASIAAAGIgBAGQADAKAIAHQAHAAAJABIAJAAQAGgBADABIAMgBQAMADALgDIAOAAQAKAAAKgEQAGgEACgJIAEgQIADgKQADgFAGAAIAEAEIAEAEQABAMgEAMQgBAIACAGQABALgDAKIgEAEIgIABIgDABIgDAAQgJABgGAAIgIAAIgPABIgPgBg");
	this.shape.setTransform(74.6281,119.4399);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AJdCWQgJABgIgBIgDgBQgOACgPgBQgPgIgKgPIgFgFIgFgHIgEgDQgCgMgDgFQgCgCgFgCQgFgDgCgCQgJgMgIgIIgGgDIgDgFIgNgMQgFgJgDgJIAAgDQgBgDgGgCQgGgCgCgDIgBgGIAGgDIAJAAIAegEQAcgNAMgdQACgEAAgIQAIgLADgIIAAgFIgBgDQgPgIgKgPIgEgHIgEgCIgEgFQgGgDgGgCIgIAAQgJgCgPABQgQABgGAFIgEAGIAAAdQACAHgCAHQgBAMABAMQABACgCADIABANQACAGgCAFIAAAIQABAEgBAGIAAAKIAAAOQACAPgCAPIAAAHQgBAKABALQACAMgCAYIAKAHQAFABALABQAJABAAAGQACAEgCAEQgIAFgKgBIgHgBQgHACgJgCIgJgDQgGgCgEABIgIADQgDABgEgBIgHgBQgSAFgSgFQgDgFACgGIAKgFIAFAAIALgDQAGgCACgDQAEgFACgRQABgPAAgIQACgNgBgDQgDgJgBgLIAAgVQAAgOABgHIAAgFIABgOIAAgYIAAgGIABgUIAEgFQADgDAAgFQgFgEgCgGQgCgDABgKQAAgIgCgEQgHgHgIgBIgLAAIgHgCQgDgEAAgFIADgGIAEgDQANAAAJADQAHABAGgBIADAAIAOAAQAMgCAQACQAFABAMgBIAHAEIAGADQACABAIgFIADAAQAFABAGgCIAFABIAIgDQAEgDAEABIAQADIACABIAEAAIAMAIIAEABQAQAKAIATQAGAOgBAPIAAAGQgFAVgEALQgJATgRALIgMAKIgMAHQgJABgCADQgDADAAAFQABACAEADIAEAHIAMAKIADADIAAABIAGAEIAFAEIAJANIAEAKQABACAFABIAKALIANARIACAEIAEAEQAFAGALAEIAKABQAOAFABAEIAAACIgIAIIgFABIgFgBgAEYCWIgKgBQgHACgHgCIgDAAQgOACgMgDIgFABQgKAAgMgBIg2AAQgRABgQgBQgHABgDgBIgFgFIAAgGIAFgGIAHgDIACAAQAMgFAHgLQACgLgBgIIAAgNQABgFgBgEQgBgJAAgHQACgOgBgSIgBgGQgBgRACgIQABgSgBgTIABgEIAAgJIACgGQACgJgEgLIAAgOIABgFQAAgFgBgFQgEgKgJgCIgGAAQgJgBgDgCQgGgCAAgGIAFgIIAFgBIAFgCIARADIAFAAIALABQAFAAAEADQACABADAHIAHAHIABAAIAFgCIAFgIQADgGADgBQACgBAEABIAIAAIAGgCQAEABADgBIASgBIAJAAQAKgBAJABQAEABALgBIAJAAQAKAAAIAEIADAEQAGAFAEAJQADAYgEAWIgCACQgDADgHAAIgEgDQgCgCgBgDIAAgEQAAgTgFgGQgDgFgHgBIgOgCQgOgEgYABIglADIgEADQgCACAAAEQgCANACANQgBACABAHIAAAKIAAAIIgBAFIAAARQgBAIACAGQADAFAGAAQADADAMgCQAOADATgCQAUgCAGgGQACgCACgLQACgJAGAAQABgBAFABIAFAGQADARgEAQIgFAGQgDADgBAFQgBADACADIADAFQAHAJAAAKIgHAHIgHAAQgGgEgBgDIgBgJQgCgIgFgHQgIgEgIAAQgdgCgdACIgHAIIgBAVQgIAfACASQADAbAWAGIAFAAQAOABATgBIAHAAQAOABANgDIAIAAIANgEQAEgCADgHIAEgWQAEgOAIAAIAGADQACABAAAEQgDAEABALQABANgBAFQgBAFgDAGIgDACIgCACIgBAHQgBAEgDADQgGAEgHADIgDAAIgHAAgAiTCSIgJAAIgIAAQgGABgGgCIgEABIgMgBIgMAAQgTACgUgCQgDgFAAgCQAAgCADgEIADgDQADgCAIgBQAIgBACgDQAGgKgEgMQgCgKgEgIQgEgFgCgHIgEgLIgKgIIhkAAIgNARIgGALQgHAHgFAJQgCALADAMQAFAEAIAEIANACQAHACAAAIIgFAHQgMACgSgCQgIABgEgBIgCgBQgGACgEgBQgFgBgMABIgSAAIgFgIIAAgEQAEgGAIgDIAHgBQAJgGAGgIIAEgJIAIgOQACgDAAgFIADgDIAAgDIADgDIABgGQAXgvAfhJIADgEIACgGIAOgeIAKgJQAHgGABgDQACgDgCgGQgDgHABgEQABgGAEgGIAEgDQAMAAAFAGQACAEAEAMIASArIARAnIAFAPQAPAgAcBGIANAiQAKASAPAFQAHABAJgCIAFABQALgCAGgIQABgDAAgHIAAgKQADgZgDgZQAAgPACgOQABgHgBgHIABgLIAAgKIABgMIgBgGIACgMIAAgFQgBgFABgDQADgIgDgIIgCgFIAAgIQABgJgBgJIAAgHQgDgKgMgEIgNgBQgIAAgBgGQgBgCABgFQAEgEAEgCQAEgBAJACIAUABIAJAAQAGgBADABQAFACAEgBIAOgBIADABIAbgBQAcgGAdAJIALACIADADQAHAFALALIAIAFIAEABIAEABQAFAGADAFIAAABQAHAbgGAaIgBAHQgBADgGAEQgFAFgCAEQgDAEgEAKQgEALgDADQgIAHgKAEIgNAGQgGACgHAAQgUAFgZgEIgBgCIAAgDIADgDQACgBAIgBIAKgCQAYgKAQgUIADgDQAFgJACgIIAAgHQAGgKABgGQABgDgDgHIgFgJQgCgHgFgMQgNgPgRgFIgHgBQgSgFgTAFIgFAAQgJACgHAAIgEAEQAAAGADAJQAEAKAAAHIAAAqQgCANACAMQABAJgBAIQgBAIACAGIAAAUQgCAQACAPIAAAVIAAAJQgBANACAMQAFAEAJAEIADgBIAJABQAFABACADQACAFgBAGQgJAGgOgEQgVgFgEAAIgIAAQgHACgGgBQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAIgbAGIgPABIgMgBgAlCgHIgGAMQAAAEgCACIgDAFQgCAEAAAEIADACQACABAHgBIAKAAQAFABAFgBIAwAAIAEgDQAAgIgEgIIgBgEIgEgEIgCgJIgPgjQgGgQgIgOIgDAAIgcBEgApKCQIghAAQgCgEgBgFQADgGAHgCIARgDQAKgDAAgJQABgBgBgEIAAgHQACgMgBgIIAAgIIAAgKQABgGgBgNQAAgNABgGIAAgPQABgSABgGQAEgJgBgJIgFgQIAAgHIAAgMQgBgIABgLQgBgGABgFQACgMgDgKQgGgIgLgCIgIAAIgJgDQgCgDgBgGIAIgHIAAgBIAWACIAWABQATgBAOABIAJAAQAFACAMAAQAMACAMgFIAKAAIAKAAIAMABQAIABAEABQAlANALAVQAEALACAMQABATgFAQIgDANIgGALIgCAFQgUAZgeANIgFAAIgGADIgRADQgHACgJgBQgFABgGgCQgGgCgBgDQgCgCABgFIAIgGQAJgCAJACQALABALgBQACgCADAAQAAgBABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAIgHQALgRAGgUIAAgEIABgEIgDghQgFgSgOgMQgDAAgCgCQgIgEgOgDQgSgEgUAGIgGACQgHAFgBAHIgCARQACAGgBAJIAAAFQABAFgBADQgCAKAAANIAAAMQgCANAEAOIAABIIAAANQgBALACAJIAAAGQgBADABACQADAHARAGIAKABQADABADAEIAAAHIgEADIgFABQgEACgKgCIgOgEIgJADIgNABQgIABgGgBIgDABIgDAAIgGAAg");
	this.shape_1.setTransform(75.025,15.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(40));

	// Wasp (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AAYFRIAAgDIgBgFIAAgMIgCgGQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAIABgDIgBgHIABgBIgDgCIAAgCQgDgFAAgCIAAgGIgEgDIgBgCIgEgDIgBgDIgEgCQgEgGgCgCQgHgCgBgCQgBgGgCgCIgFgDIgDgDIAAgEQgBgJgGgJIgEgCQgIgHgEgGQgCgHAGgBQAIAAAAgBQAAgBgFgCIgEgCQgCgBAAgEIAAgEIABAAIAAgCIAAgGIACgFQgCgDABgDIACgDIAAABIABAAIAAgCIgBAAIADgFQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAIAAgFQABgBABAAQAAAAABgBQAAAAABAAQAAgBAAAAIABgEIAEgFIACgEIAFgHIADAAIADgDIAKgJIAGgDIAEgEQAEgCAEgEIABgFIAEgEIgCgGIAAgDIgFgMIgBgHIgCgGQgCgDgEABIgCADIgDAAIgGADIgLAAIgHgDIgKABQgHgDgGAAIgGAEIgFABIgDAGIgGAFIgDABQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIgGALQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAIgEABIAAAFQgBADgDACQgEADgDgCIgEgGIgBAAIgCAGIgBADQgCABgEgBQgFAEgDAGIgBAPIAEAFQACAEgBADIgDADIgDACIgDgBQgBAAAAABQgBAAAAABQAAAAAAABQAAABABAAIABAGIgDAHQgEABgCAAQgIgKAGgLIAGgDIADgIIgEgDQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAABAAAAQAAAAAAABQAAAAAAAAQACAEAAADIgCABQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAQgCAAgFAIQgNACAEAGIABAAIAGgFQAFACABAEIAAAFIACADIgBAEIABAGQABADgCADIgHAAQgFgBgCABIgDAGIgGACIgCADIgBAEIgDADIAAAFIgCAFIgBAFIgEAEIgCAGIgOALQgCABgHABIAAAFQgDAIgFAFIgDABIgDAEIgFADIgGALIgJALQgCADABAIIgCAKQAAADADAEQABACgCAEIAFAHIACACIABADQAJACABAFQgDADgGAAIgBAEQgGABgHgEQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAQgJgBgJgFQAAgEgEgCQgCgBgDABIgFAAQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIgCABQgEgFgBgFIAAgFIgDgCIgCgIIAFAAQACABACADQAFACAIgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAgFIADgFIABgGIAAgEIADgDQgBgHAGgGIAJgKIABgEIADgCIACgFQAGgGAIgBQACgEAEgBQAFAAABgCQABgCAAgDQgCgFABgCIAFgMQAJgIAEgFIAIgKIAIgDQABgBACgEIABgEIAGgDQACgGgFgEQAAgMAKgFIAFgFQAEAAACgCIAFgFQADgIADgCQAQgJAHgGIADgEIAEgDIACgFIAGgDIAIgJIAEgCIACgEIAEgCIABgDIAEgDIAHgEQAEgDAEAAIAEACIABADIADABIACgBQAAgKAEgCQAJAAADgCIABgCIAGgCIACgCQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQANAAAHgBQACgFgBgFIgCgJIAAgDIAAgDIAAgGIgEgMIgCgLIgFgFQgBgGgEgCIgEABQgDALgDAXIgFAMQgBAHgEAGIgKAGQgEAFgDABIgVAFIgFgBIgHABIgMAAIgLgBIgGACIgHAAQgIADgGABIgIABIgLAGIgMADIgGAFIgFACIgHAFIgFAAIgFACIgIAAIgbAFQgHABgGgBIgGAAQgIgBgGgDIgGgGIgDgBIgBgEIgDgDIgDgVIgJACIgFADQgGAAgFgCQgDABgEgBIgOgEIgFABQgIgBgGgEIAAgGQABgFgBgCIgDgEQgFAAgDADIgGgCIgFABIgGABIgKgDQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAIgEABIgDgDIgCgBIgEgEQgFgCgCgCIgCgEQAAgEgCgBQgEgDgEADIABAFIAAADQgEABgDgCIgEgFIgHgGIgFgHIgEgCIgBgFIgDgCIgFgHQgGgDgBgCIgBgGIACgEIADgKQgDgJABgEIACgCIADgDQAEgJACgCIAEgDQAEgCABAAIACADQAAAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAFgDAFABIAEABQACAAADgEIALgCQAEgBAEACIABAAQAJgFADADIADAAIACADQAAAAABABQAAAAAAABQAAAAABAAQAAAAABAAIANAAQACABACAFIAEgCQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIgEAEIAAABQADgBACgEQADAAADgCIAFAAIACgBQAGgBAIADIAJgBIAIACQAGACADgBIAEgCIAGADIAKABIAEADIAHAAIAKACIAFgBIAOAHQAGgBAEgEIAEgDIAUgCIAEADIAFABIAEgCIAPAAIAFgCQAEgCABABIAJADQAEABAEgBIAMgBQAIgBgBgDIgSgHIgPAEIgEgBIgQABQgJACgJgBIgDgCIgGAAIgHgCIgIgCIgEgFQgCgDgEgBQgDACAAADIAAAFIgDAAIgEgDIgGgEIgFgGIgCgBIgIgFIgEgBQgFgEgFgCIgDAAIgEgBIgFABIgDgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAIgDABIgDgDIgHgCQgGAGgKgCIgCAAQgEgDgCACIgFADIgGAEIgCADQgDAEgGgHQACgIADgIQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIgBgEIAAgKIgCgGQAAgCAEgEIADAAQgBgEADgBQAEgBABADIACADQAAABAAAAQAAABABAAQAAABAAABQAAAAAAABIAAALQADAGADACQAFAEAHAAIAFgBIACABQAAAAABAAQAAAAAAAAQABAAAAgBQABAAAAAAQAFgBAGACIADgBIAEgBIABACIACAAIADgEQAGAAAEADIAIAFIAMAFIADADIAEABIAFAGIAGABIAEADQADABAEgCIAFgDQADAAAFACIAEgBIAFAAQAEABAGAEQACABADgBIAEADIAJACIAHADQADAAAGgDIAIAAIAJgCIAFABIAEgCIAHABIAFgBIAGADQADAAAFgDQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQACABAEgCQAEgBAEAEIAHAAIAEAAIAEAAIADgCIASABIAFACIAHgBIAHAAIABgBQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgCgDIgCgHIgFgEQgEgIgBgFIAAgIIgCgDIgCgMQABgDAFgBIAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAQgBAAAAAAQgEACgFAAIgGgJQgBgFgCgDIgHgHIgDgHIgFgGIgCgGIgGgEIgEgFQgEAAgDAFIgFAEIgDAFQgBACgFABIgHABQgEADgDAAQgDgCgBgFQgBgEADgEIAKgKQAHgHgCgHIgGgHIgCgGIAAgEIgDgFIgEgMQgBgDADgFQADgFADABQADAAAAAKQABAKADACIAGgFQADABAFAFIAFAIIADAHIACAAIACgIQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABAAIADgEIAFgDIAFgDIAHgCIADgCIALAAQABgEAEgBIAHAAQAGgCAIABIAIABIAMAGIAEABQADACADANIAAAFIAEAGIAFAMIAAAFIABADIABAHIgBAHQgBAHACAIIACACIAEAEIABABIACABQABgBACgIIAEgGIAAgCIADgMQgBgHABgCQABgCAHgDQgBgCABgDIADgFIAAgFIABgDIABgHQAEgKAHgJIADgGIAGgCIAEgDIAegBIAEABQAEABAJgBIAJAEIAEAAIAEADIAGADIAEAAQADgBADABQACABACAEIAHADQAEAEAGADIAFACIAEAFIACADQAFAFADABIACACIADABQAEgCACABIAEAEIACADIAAAFIADADIAEAIIADACQABAMgEAKIgFAFIgBADQgCAFgFACQAAABgBAAQAAAAgBAAQAAAAAAAAQgBAAAAgBIgDgDIgEgCQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAIADgGIABgFIADgEIABgFIAAgFIADAAIAEADIACAAIABgBQgCgFgDgBIgIgBIgFgDIgEgBQgEgFAAgHIgEgBIgFADIgEAAIgKACIgGAFIgFACQgCABgBAEIgCAHIgHALIAAAEIgCAGIgDACIgDAHQgCAEgDABIgFADIgDADIgFACIAAAHIgBADIAAAGIgFAFIgEAKIgDAEIAAADIgIAKIgGADQgEACgDAFQgDAFABADIABACQAEABADgFIACAAIADAAIAHAAIALgFIAEABQABAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAFgDIAKAAQAGgDAMgBQAFABAJAFQAEABADgFIANAAIADgBIAEAAIAJgFIAJgBIAJgFIACAAQAFAAAFgBIAGgFIAEAAIADAAIAHgEIAHgDQAIgCAIgBIAHgEQALgCAKAAIAGAAIACgCIAEgBIAEABIAEABQADgBACgEIAPAAQAJAAACgEIAAgFIADgJIADgBIABgGIAFgIQADgBACABQAGACAAAFIAAAKQABAGgBAFIgHAIIgIgDQgDAGgDABIgDAAIgIACIgGAAIgCACIgCACQgKgBgFACQgEAEgCAAQgIgBgCABQgDACgBAHQAAAHgEABIgKgBIgDgDIgIAAIgEAAIgDABIgFAAIgCACIgEACIgIAAIgKAFIgEAAQgEAAgEACIAAABIABABQACACgCADIgDgDQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAQgDACgDADQAAAFAFABQAEAAAEgBIAOgFQABgBALAAIACABQAFgCAFAAIAEACQABAAAAABQABAAAAAAQABAAAAABQABAAAAAAQADgHAGABIAIAFIAIgBIAGABIARgDQADgBAEACIACgBIAGAAIAKgDQAGAAAEACQAAAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQAGAAAJAGIAIAAIADgBIAEAAIACgCIAGABIAEADQAEAAAHgBIAKABIAOAAIAJADIACACQAAABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAEgDQAHACAAACIACAEIACABQAHACADAGIABABQACADgBADIgCAGIAAADQgCAKgEAJQgEADgFACQACADgDAEIgEACIABACQgDAGgFACIgCABIgCAFIgDABIgCABIgFAAIgCABIgCAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIgDABIgCgDIACABIABgBQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBIgDgDIgHAAIgCAFQgBAEABACIACAAIACgCIABABIAAACIABABIADgBQgFgCAEgBIAHAFIAAABQgHABgFAFIgCAFIgGAGIgFACIAAABIAAAAIgCgBIgBABIAAABIACABQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQgDADgEgDQgCACgDAAQgDgBgCgCIgCABIgBACIgFgDIAAAAIACAAIABgBIACACIAAAAIAAgBIAAgCIAAgBIgEADIgGgCIAAAFIgFgCIgCAAIgDAAIgCgCIgFAAIgFgDIgDAAIgEgDQgDgBgDACIgDAEQAAAAgBAAQAAgBgBAAQAAAAAAAAQgBAAAAAAIgCABIAAABIADAAQAAAEgDAGIAAADIgDALIAAAEIgEAFIgEABIgBAFIgEAAQgDADgCAAQgDgDgEAEQgFAEgCAAQgEgBgDgEIgBABQAAABgBAAQAAABAAAAQAAAAAAABQAAAAAAAAIgBAAIAAgCIgCgBQgBAAAAABQAAAAAAAAQgBAAAAABQAAAAABAAIABACQgEAAgFgCIgBgFIgBAAIgCAEIgHgDIgDgDIgEgBIgHgFQgDABgEgEQgDACgCgBIgFgDQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQgCgDgCgBIgFAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQgEADgFgBQgCgBgEgEQgEgDgEgBIgFAAIgEABIgHgDQgDACgCgBIgGgDIgFgBIgGgEIgIgBQgBgBAAgBQgBAAAAgBQgBAAAAAAQgBAAAAAAIgCAAIgDgCIgFAAQgKgDgHgFQgJgIgFgIQgCgFgFgFIgFgBQgFgEgFABQgBABgBALIgDAIIAAAHIgDAFIAAAEIgBAFQgBABAAABQAAAAAAABQAAABAAAAQAAABABAAIAFACIAGABIAGAAIAGACIACAEQAFAAAGAEIACACQAAAAABAAQAAABAAAAQABAAAAAAQABABABAAQADABAKgBIADAEIACADIgBAFQABACADACIACAEIADAEIAHAFIAHAEIAKAOIAFAEIACAHIAEAEIACADIAGACIACADIABADIAEABIAFAFIABAKQACAFAIAGIABADIABAFIADAEIAAADIADAFIACAAIABgBQACgDgEgFIABgEQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQACgDADgBIAJAEIAJAGQAEAEgCAGIgEAGQgBAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIAFgCQADgBADABIAEAFIAJAHIACAEIAIADQAGAGAFAJQABACAFABQAEAEACAEIgBACIAAADIABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQADABADAEIAEAHIACABIAFAEIAIABIAEAIIABAAIABABIABAEIADABIAAACQADgBAEAJIAEACIAAADIACAAIABABQACACAAAGIACACIADAFIADAGQABAEACABIAFgEIABgDIACAAIAAAAQgCAGAEAEQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgCAAQgDAFgDgCIgCAAQgDACAAADQAAAAABAAQAAABABAAQAAAAABAAQABAAABAAIABABQAAABAAAAQAAAAAAABQAAAAgBABQAAAAAAABIgBAAQgBgDgCgBIgDABIgBgBIgBgEQgEAAgDgDQABgFgEgDQAAAAAAgBQAAAAABgBQAAAAABAAQABAAABAAIAAgDIgCgBQAAgEgBgCIgBAAQgBACgEAAIgBABIgBAAIgBgEIACgCIgCgBIgBAAIAAADIgBAAQgHgFABgDQAEABADgBQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAAAAAAAIgFgBIgBgEIgBgCIgDABIgCgDIgBAAIAAADIAEAAQgCAEAFADIAAACIAAAAIgIgHQgGgGACgCIgGgGIgDgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgDgCIgBgCQgKgGABgEIABgCIAAgBIgBABIgCAAIgDgDQgBAAAAAAQgBgBAAAAQgBAAAAABQAAAAAAAAIgFAEIAAAAIgCgDQgBgBAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIABABIABAAIAAAAIgBgCIgBABIgBgBIAAgDQgEgEgEgIIgDgCIgDgBIgDgDIgHgDIAAgBIACgBIAAgBIgBgCIgCAAQAAABgBAAQAAAAgBABQAAAAAAAAQAAABAAAAIgBAAIgDgEIgEgDIgDgBIgBgCIgEgEIgCAAQgGAHgGgDIADgGQADgDgBgEQgCgCgFgBIgHgDIgFgIIgEgDQgGgFgCgFQgBgHgEgDIgFACIgEgCQgDgJgEgBIgCAEQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBgBIgFgHQACgIgBgDQAAgCgGgFIgEgFIgGgEIgCgDQgFgBgEgCQgBgBgBgGQgCgGgCgCQgCgCgFgBIgIgEIgDgEIgIgBIgEgDIgLAAQgBgBgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgDAAIgDgCIgDAAQgDgEgDgBIgCABQgHAOgCAMIAAAGQgBABAAAAQAAABAAABQAAAAABABQAAAAAAAAQACACAEAAIAFAEIAJADIACACIAEACIAEAEIAEABIADAFIAMAIIAFAJIAGAFIABAFQAFAFABAHQAAAHgEAGIABACIAGAAQADgBADAEQADAHgBAJIgDAFIACAFIACAHIACAFQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAABIgCAEQgCACAAAEQgBAEgGAEQgGAEgBADIAAAFIgBACIAAAEIgDAHIgDACIgCAFIgEAFQgDACgGAAQgGgBgCACIgGAHIAAAEQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgEgCgBABIgDADIgCABQgCACAAAHIgHAHIgCACQgCADAAAGIgBACIAAADIgCAIIgDAPQgEAAgDgCgAFQEnIABAAIAAgDIgDgCIAAAAIAAgCIgBAAIgBADIAAADIADgBIABACgAAREZIAAAAIABAAIAAgBgAE9EEQgBAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAAgBIAAAAgAErD3IACAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAIgBAAgAETDmIAAAAIADACIACAAIABgCIgBAAIgBAAIAAABIgBAAIgBgCIgBAAgAgEDlQAAAAAAAAQAAABAAAAQAAAAABABQAAAAABAAIAAgBIAAgCIgCAAgAgBDhIABACIAAAAIAAgDIAAAAgAEPDhQAAAAABAAQAAAAAAAAQAAAAAAgBQABAAAAAAIgCAAgAEMDeIACgBIgCgBIgBAAgAAADVIAAAAIAAgBIAAgBIgCAAIACACgAAADNIAAgBIAAAAgAgJDGIAAADIABAAIAAgBIABAAIAAgBIgCgCgAAJDBIADAAIAAgBIgDAAgADkC0IABAAIAAgBIgBAAQAAAAgBAAQAAAAAAABQAAAAAAAAQABAAAAAAgAgCCnIABAAIAAgCIgBAAIgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABAAgAgZCUIAAAAIAAAAIACgBIgBgBIgBAAIAAACgABkCQIABAAIAAAAIgBAAIAAAAgAAiBzIABAAIABAAIgBgBIAAgBIgBAAgABoA6QABAEAEABQAFgDAAgFQgBgDgEgBQgFADAAAEgAjsA1IgLACIgBACQABADADABIADgCIAFAAIAHgCIAAAAIAJAAQAEAAADgEQAAgGgKAAIgDACIgCAEIgDAAIgDAAIgCAAgAEUA2IABAGIABgBIgBAAIAAgGIgBAAgAkQAqQAAAAAAABQAAABABAAQAAABAAAAQABAAAAABIAAAFQACAEAFgCQAEgBACgDQAAAAAAAAQABgBAAAAQAAAAgBgBQAAAAAAAAIgEAAQgDgBgGgFIgBAAgADyAiQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABIACACIAEgBIABgCQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBgBAAAAIgEgCgAkPAhIAEAEQAEAAABgDQAAAAAAgBQAAgBAAAAQgBAAAAgBQAAAAAAgBIgEgBIgDACIgBAAgAj7AhQAHABABgHIgBgBIgBAAIgFACQgBAAgBAAQgBABAAAAQgBABAAAAQAAABAAAAIACABIgBAAgAExAaIABACIAAgBIAAgBIgBgBgAhvAXQAAAAABAAQABAAAAAAQABgBAAAAQAAgBABAAQAAgDgDgDIgDAAQgCAFAEADgAi9ASQADAEALgBQAKgBAAgGQgCgEgDAAIgIABQgFgEgEAAQgGAEAEAHgAETARIAAACIABACIAAgBIACgBIgBgCIgCAAgAjlALQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAABAAQABAGABABQAHACAGgEIAAgBQAAgBgGgCIgEgFIgBAAIgDACgAGEAUIgBAAIAFAAIAAgBIgEgBIAAACgAjIASIAAABIABABIACAAIAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAQgBAAAAAAgAlBAJIgBAIIADABQADgCADgEIAAAAIAEgCQAAgBAAAAQABAAAAgBQAAAAAAgBQAAgBAAAAIgBgFIgCAAQgDAFgHADgAiZAOIABACIACAAIABgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBgBAAIgBAAIgCACgADGADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBADAFAEQAEAEACgBIAAgBQACgIgGgFIgBAAIgCACgAD1AHIAAABIACABIACgBIAAgBIgCgBIgBAAgACgAEIAAADQACADAEgCIABgBQAAgDgFgCgAiYgEIgEAEIAAAEQADAEAEgCIAEgEIAAgCQgBgEgEAAIgCAAgAiDgXIgDAEQAAAEAEAFQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQABAGADAEQAOACALgFIAAAAQAAgGgGgEQgEgCgDAEQgBADABADIgBABQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAIAAgEIgIgEIAAgCIAAAAIAKAAIABgDQgCgEgFgDIgCAAIgCgDIgDgCQAAAAgBABQAAAAAAABQgBAAAAABQAAABABAAgAEIgBQAAABAFAAIACADIAHABIACgDIAAAAIAAAAIAAAAIAAAAIgDgBIgEAAIgDgCIgFAAgAEoACIACACIAJgBIAAgCQAAAAABAAQAAAAABAAQAAgBAAAAQAAAAAAgBIgFgBQgJAAgBACIgBACIACAAIABAAgAEdADIABAAIAAABIABgBIgBAAIAAgBIgCAAgAjygHQgDAHAEADIABAAQACgDABgCQAAgFgEAAgAFTgEIgBABIABADIABAAIACgDIAEABIAAgBIgBgBIgCAAgAhcgGIABADIAEABIABgBIABAAIAAgBQgCgEgDAAgAGWgEIAAABIABAAIAAgBIABAAIgCgBgAGLgGIABABIAAAAIABAAIgBgCIAAAAgAFggIIAAACIABABIACgBIgBgDIgCAAgAD2gSQAAAGAFAAIAEAAIABABIADADQACACADgCQgBgFgEgEQgFgDgFAAIgCAAgADpgJQAAAAAAAAQABAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIgJgBIgEAAIgCgDIgKgCIgCABIAAADQAFADAFABIAGADQABAAAAAAQABAAAAAAQABAAABAAQAAAAABgBIAFACgAFwgMIAAACIABABIADAAIAAgDIgBAAgAFdgMIABACIABAAIAAgCIgBAAgAFggNIAAABIABAAQACgCgBgDIAAAAgAFFgQQAAAAAAABQAAAAABABQAAAAAAABQABAAABAAQAAABABAAQAAAAABAAQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQgBgEgDAAQgCABgCADgAkIgQIAAABQAAAAABABQAAAAABABQAAAAABAAQAAAAABAAIAEgBIgBgBIAFAAIAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAQgCACgGAAgAFagNIABgFQAAgDgEgBIgCABQgBAEADADIABAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAgBgAmpgTQADAHAEgCIgBAAIACAAQAEgDgDgFIgBgDQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAIgBgCIgDgBQgDADAEAHgAikgPQACABAEgDIACACQAOgCgDgHIAAgBIgDAAQgHAFgHACIgCgBgAg+gSIAAABIABAAIAAgBIgBAAgAEjgSQADACADgBQAEgGgEgGIgCAAIgDACIgDADIAAAAQgBADADADgAEYgUIAAABIABACIABAAIAAgCIAAgBIgBAAIAAgBgAEzgZIAAABIAEADIADACIADABIAEgCIAFgCQAAAAAAAAQABgBAAAAQAAgBAAgBQgBAAAAgBQgGgEgFAAgAAwgVIAAABIAAAAIABAAIgBgBIAAAAgAFlgaQAAAAAAABQAAAAAAABQAAAAABABQAAAAABABQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIgCAAgAjKgZIAAAAQAAABAAAAQABAAAAABQABAAAAAAQABAAABgBIAAgBIgCgCIgBAAgAhcgYQAAAAABAAQAAgBABAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAIgFgCIgBACIAAAEIAAAAQABABAEABgAEagcIAAADIABAAIABgCIgCgCIAAABgAhSgeQAAABAAAAQAAABAAAAQABAAAAABQABAAAAAAIADgBIAAAAQAAgBgBAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgCAAgAFxgwIgCARQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAQAEABAEgDIADABIAAAAIADgDIAAgCQgHgFgBgCQgBgHgCgCIgDAAgAFmgdIABAAIABgBIgBgDIgBAAIAAgBIAAAFgAmwgeIABAAIAAgBIgBgBQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAABABgAmUgkQAAABAAAAQAAABAAAAQAAABAAAAQAAAAABAAQAAABAAAAQABAAAAAAQAAAAABAAQAAAAABgBIACgCQAAAAgBgBQAAgBAAAAQAAgBAAAAQgBAAAAgBIgCAAgADhg1QgGAEAEAFIAIAEIAGAAIAAABIAEADQABADAEABIAAgBQACgHgEgFIgCAAIgCABIgGgEQgDgGgFAAgAEYgjIACAAIAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAgAlngrQgDACAAAEIADACIAIgBIAKgBIAFAAIAEABIgBgBQABgEAHAAQAHAAABgDQAAAAABgBQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAIgEABIgFAAIgFAFIgRACIgEgBIgDABgAFdgmQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIACgCIgBgCIgBAAgAjhgkIABABIABAAIABgBIAAgBIgDAAgAmwglIABABQABAAABAAQABAAAAAAQABAAAAgBQAAAAABAAIAAgBIgEgBgAl6grQgBAAAAAAQAAAAgBABQAAAAAAAAQAAABAAAAIACADQAEABAEAAIACgCQgBgBAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgGgBgAD6grQgBADADACQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABgBIAEABIACgBIABgDQgDgDgDAAIgBAAQgEAAgCACgAGgg8QAAAAAAABQAAAAABABQAAAAAAABQABAAAAABIADADIgBAJQgBAGAFAAQAEgCAAgEQADABAEgEQAEgDgBgEIgCgBIgBgBIgDgEIgJgDIgEgIIgFgEIgCgDQgBgCgEgCQgFgCgDACIgDAEQgJgJgEgBIgCAEIgEADQAAAEACACQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABgBIAFAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAABIACADIADgBIAFAAQABAEAEAJIAAADQAAAAAAAAQAAABAAAAQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAABgBIADgDgAi1g8QADABAFAFIAGACQADABAAADIgDADQAAABgBAAQAAAAAAABQgBABAAAAQAAABAAAAQACADAHgBQAHgBACgCIAAgBQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAgBgBAAIgEgCQAAgFACgEQAEgBAEgEQAEgFgDgEQgDgEgGAAIgEABIgEAAIgDAFIgEADIgJgDQgJACgFgBQgFgDgCABQgCABgCAGQgBACgFACQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAEAFAEgEIACgDIAAgDIABAAIAEABIAFAAIAGgBIACAAgAEYguIADAEIAAACQAAABABAAQAAAAABAAQAAAAABAAQAAAAABgBIACgCIACgDIAFgEQABgCgCgEIgEgCQgCgGgGAAIgKACIAAABQgEACAAAFQAAAEACADQADAAADgCgAFAg1IABAFQADACAEAHIAFgDIgBgBIAAgBQABgEgDgDQgCgDgEgBgAmpgrQAAABAAAAQAAABAAAAQAAAAABAAQAAAAABAAIABgBQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAAAgADJgqIACABQADAAADgDIAFACQAEAAAAgEQABgEgCgCIgJAAIAAAAIgBAAQgHADABAHgAhsgvIAAABQAAAAAAABQAAABAAAAQAAABABAAQAAAAABABIABAAIACgCQAAgDgDgCgAnFgyQgEABABADIACADQACACAEgEQAEgDgCgEIgBAAIgGACgAE2g1QgBABAAAAQAAABAAAAQAAABAAAAQAAABABAAIADADIAEgEIgDgDIgDgBgACNg5QAAAFADADQADADAEgCIABAAQACgDgCgFQgDgFgDgBgAGFg8QAEAJAEACIABgBIAAAAQAAgJgEgIIAAgEQAAAAgBAAQAAAAgBgBQAAAAgBAAQgBAAgBAAQgEADAEAJgAmdg7QgBAEAAAEQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAGgDIAEAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBABAAIABgDIgCgCIgFABIgEgCgACvg2QAGAAADADIABAAIABgFQgCgDgDgDIgDAAQgHADAEAFgAiOg3IACADQAGAAgCgGIgDgBQgBABgBAAQgBAAAAABQAAAAAAABQgBAAABABgAhgg3IABABIABAAIABgBIgBgDIgBAAQAAAAAAAAQgBAAAAABQAAAAAAABQAAAAAAABgAlzg+QgDAGAGACIACgDIABAAQAGAAAGgDIAAgBIgCgDIgHACIgEgCgAFrhNQgCAFgCAAIgGACIAAABQAGACAHAFIADAHIAEAAQABgHgDgGIgDgEIgBgEQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAAAAAgAk6g6QACADADAAQABAAAAAAQABAAAAAAQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgCgCgDAAQgDACAAADgAD7g3IAAgBIgCgCIgBAAIAAACIgBAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAABAAgAm/g5IABAAIAAgBIgBAAgAlPg7IAAAAQAAABAAAAQAAAAABAAQAAAAABAAQAAAAABAAIABAAIAAgCIgBAAIgBgBgAlBg8IABABIACAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAIgBAAQAAAAgBAAQAAABAAAAQAAAAAAABQAAAAAAABgADRhCQgBAEADABQAEACACgCIAAgDQgBgCgGAAgAlghDIAAAEQABACAHABQAGAAACgBQAAgBABAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIgGgCIgBADIgBAAIgBgDIgFgCgAEEg8IACgBIABgEQgCgCgDgCIAAgBQACgEAHAAQACgBAEgDIAJAAQAHAAADgBIABgCIACABQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAABAAIgDgDIgGACIgKgBQgEACgEgBQgDAAgCgEQgDgDgDAAIgEABQgFAGgEgBIgFgCQgCABgCADQgDAEgCABQgGAAgDgFQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQgCgCgIADIgBAAIgBACIAAABIAIABIACAIQABADADADQAFgCAGABIAHADQAAAAABAAQAAAAAAAAQABgBAAAAQABAAAAgBIADAAQAGAAAFAGgACohAIAAADIABABIACAAQAEgFgDgBIgBAAQAAAAgBAAQAAAAgBABQAAAAAAAAQgBABAAAAgAE9g+IAAgCIgNgEIAAAAQgDACABAEIADABIACgBQADADAHgDgAm/hUQABAHgDAHIgEAEQgCACABADQAAAAAAAAQABAAAAAAQABAAAAAAQABAAABAAQAGgDABgIQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAIAFgBIAAAAIAIgEIAAgEQAAgBgBAAQAAAAgBgBQAAAAgBAAQgBAAAAAAIgGAAIgCgBQgFABgBADgAj5g/IAAABIABAAIAAgBIAAAAgAkIhBQAAABAAAAQAAABABAAQAAAAABAAQAAABABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAgBAAQAAgBAAAAIgCgCIgBAAIgBADgAHFhBIACACIABgBQABgDgBgDIgBgBIAAAAgAFKhCIACAAIAAgCIgBAAgAmChMIgBADQADAGAHgCIABgBIgDgHIgDAAgAFXhIQACADAEAAIABAAQABgDgBgEIgFgCIAAgBQgFADADAEgAE7hHIABABIABAAQAAAAABAAQAAAAABAAQAAgBAAAAQABgBAAgBIgBgCIgDAAQgBAAAAABQgBAAAAABQAAAAAAABQAAAAABABgAEihKQgBAAAAABQAAAAAAABQAAAAAAAAQABABABAAIAAABQADAAACgDQAAgBgBAAQAAgBAAAAQgBAAgBgBQAAAAgBAAIgCACgAG3hKQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAIACgBIgBgDIgBAAgADBhMIABACIAFAAIADACQAEgBgBgEIgFgEIgEAAQgDABAAAEgAHMhKIACgCIgDgBgAnEhRIAAACQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAIAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAgAgZhUIAAABIABAAIAAgBIgBgBgAgVhiQAAgDgCgDIgDgEIgEgHQgHgGAAgEIABgDIgEgSIgDgEIgCgIQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQgDAFAAADIACAFIAHARIAAAFIACADIABADIAFAFQACAFADADIAGAGIABACIABAAgAALhmIAAACIACACIACAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAgADNhrIAAABIABAAIAAgBIgBgBgABTiPQgEAFgCAEIAAADIAAAEIgDAEQAAABAAABQgBABABAAQAAABAAAAQABABABAAIACgBQACgGACgDIAAABIAGgGQAFgGAAgCQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAIgGABgAAbiIQABAEACAAIABAAIgBAAQAAgBAAAAQABAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAgAlAiFIACAAIgCgCgAAFiTQgEABABADQAAABAAAAQABABAAAAQABAAAAABQABAAABAAIADgDQADgBAFACIAAgBIAAgCQgBgDgEAAIgHABgAgKikIgFAIIACADIAGAAQACACgBAEQgBAFAAACQAFgBABgGIACgJQAFgBADAEQAEAAACgEIACgGIAEgCIACACIgCAIQgBADADAEQACAEADgBIAEgKIgBgFIgBgJIADgEIABgIIABABQACgHgGAAQgEALgEADIgEAAIgEAAIgFAGQgDAEgEAAIgDgFQgBgEgCAAQgDACgEAGgAAtibQAAADACADIACABIABgBQABgGgEgBgAAqisQgBAAAAAAQAAABAAAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAQAAgBAAAAIABAAIAAgCIgBgBIgCAAgABNizIACAAIADADQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIADAEQACACAEgBIAIgQIAIgQIAGgHIADgBIAFgJIAGgFIAGgJQAFgEACgDIgCgEIAAgFIgEgEIgCgFQgCgCgDAAIAAABIABAEIAAAEQgDAAgDgDQgDgDgDAAIgCABIAAADIgCACQgDACgEgEIgCgGQgHgGgIgCQgFAGgCAAIgEAAIgFACIgCAIQgBAFgCABIgCAAQgDAAgDADIgBAFIgBAFIgCACIgBADIgDADIgDAHIAAADIgEAJIgEANQgCAGADAGIAKACIADgCIAHgCIgBAAIACAAQAEAAAHADgAAGi2QgFAFAFAGQAFgBgDgKIgBAAIgBgBgAhFj9QgCADABACQABAEgBAEIgEADIgEADIAAAIIADADIABADIACACIACACIAGAIIADACQABACABAFIAHAGIAAAEQACAQAFgCQACgBACgDIAEgFIAEAAQAFgCADAAIAIADIAEAAIADABIADABQADgCAAgFIgBgLIgBgGIAAgGIgCgEIAAgDQgFgIgFgEQgBgBgEAAQgEAAgBgCQgCgCAAgDIgBgFQgCgBgCAFQgEABgEgDQgEgCgCAAQgEAGgGgEQgFgCAAgBIAAgDIgCgCIAAgEIgCAAgAhpjiQgCACABAEQAEAEAGgDIgBAAQAEgKgHgBIgFAEgAAwjkQAAAAAAABQAAAAABAAQAAABAAAAQABAAABAAIAEgDQAAgEgDgDIgBAAQgEADABAFgAA5jqIAAAAIABAAIAAgBIgBgBIAAACgACPjuIABAAIAAgBIgBAAgAgTkAQAAAIAEAHIAFABIABAAQABgFgDgGQgDgGgEAAgAgsj7IAAAEIABABIABgBQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBIgCAAIAAAAgAFiEtIAAABIABAAQAAgCAEgCIACgEIgDAAIgCgFIACgGIgCgCIgCAAQAAgDgCgFQAEAAADgEIAAAAIgFgEIAAgBIABgBQgBgCACgDIADgBIABgCIAFgBIAAgBQAGAAAFADQAGAEAAAFIgCADIAAAEIgCACIAAAIIgCACIgBAGIgEACIgBADIgDAAIAAAEQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgEAAIgDACQgDgGADABgAGaEUQgJgIAAgNQAAgMAJgJQAIgJANAAQAMAAAJAJQAJAJAAAMQAAANgJAIQgJAJgMAAQgNAAgIgJgAGcDsQgIAIAAALQAAALAIAIQAIAIALgBQALAAAHgIQAIgHAAgLIAAAAQAAgLgIgIQgIgIgLAAQgLAAgHAIgAG5EPIgKgPIgIAAIAAAPIgEAAIAAggIAPAAQALAAAAAIQAAAJgKAAIAKAPgAGnD9IAHAAIAIAAQAEgBAAgEQAAgFgJAAIgKAAgAhxBwQAAgEADgEQAIACABAIQgBAEgDAAQgDAAgFgGgABUhsIAAgCIACAAIAAADgAhmhuIgFgDQgPgBgJgLIgBgHIgEgDIgCgFQgGgGgBgDQgDgLAEgJQABgCgCgEQgCgDABgDIADgDIAEAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQACgCgBgEIABgBIABAAQAIACgFAQIACAEIgCAIQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIgFABQgCAFAEAEIADAAIADgEQADgDACABQAFACgBAJIgDANQAAADAEADQADADADgBIABAAIgBgFQgBgBAAAAQAAgBAAgBQAAAAAAAAQAAgBABAAQAEgCACABIAFADIACABIACAEQAGABAGgBQADgBACgDIAEgBIADgBIABgEQAGgJACABQAFADgGALQgGAMgFACIgIABQgDAEgGABIgCAAIgEgBgACPh9QgBgDACgDIAEgEIADgGIAMgLIABgHIAHgHIABgEIACgDIAIgFQAEgBADAFIACABQACACgBAGIAAAEIgFAGIgBAAQgCAEgCACIgHACIgFAGQgIADgCACIgDAGQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgFAEIgEABIgDgBgACtkCQAAgEAEgEQAEgFABgCQAHgWASgPQACgBAFgBIAHgEIAFgCQAGABABAGQgCAFgEACIgIADIgCADIgCAAQgIAHgDAGIgGAHIgBAEIgKAJQgGAIgGABgAifkLQgCgBgBgDIgCgGIgDgBIgDgBIgGgHIgKgFIgDAAQgBgBgBgBQAAAAgBgBQAAAAgBAAQAAAAAAAAIgGABIgBgCIgEABQgFgBgDAAIAAAAIABgBIgBgCIgBAAIgBABIAAABIABABIABAAIgBABIgCACIgFABIgCgBQgHgCgCgDIAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBQgBgEABgEIAFgBIAAgCIgBAAIAAgCIAIABIACADQACAAAEgEIAGAAQADABABADIABAAIAAgBIgCgCIAFgCIAFgEQANADAJAIIAEAHIAGACQADABABACIAGAGIADAEIAEABIABgBQACABAAAEIgCAGIgEACIgGAFIgFABIgDgBgAjikuIACACIgBgEgAjekuIAAABIABAAQAEgCAFABIgDgDIgHADgAi5kWIAEgDIACAAIADAEQAAADgDABQgGAAAAgFgADuk4QgCgFgCgCQgHgFAAgCQgCgGAEgFIAGgBQAFAAAFAHIADACIAGAFIAHAFIAAABIABAFQgBAAAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgBACIgDACQgJgBgIgEgAD/k7IAAAAIAAgCIAAAAg");
	mask.setTransform(72.345,67.875);

	// Color_1
	this.instance = new lib.Color_1("synched",0);
	this.instance.setTransform(150,150,1,1.0001,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleY:1},0).to({scaleY:1.0001,alpha:0},10).wait(10).to({startPosition:0},0).to({scaleY:1,alpha:1},10).wait(1));

	// Color_2
	this.instance_1 = new lib.Color_2("synched",0);
	this.instance_1.setTransform(150,150,1,1,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({scaleY:1.0001},0).to({alpha:0},10).wait(11));

	// Color_3
	this.instance_2 = new lib.Color_3("synched",0);
	this.instance_2.setTransform(150,150,1,1,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(40));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,149.3,134.9);


(lib.Logo_Container = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Logo_Stacked
	this.instance = new lib.Logo_Stacked("synched",0);
	this.instance.setTransform(11.3,-280.65,0.295,0.2965,0,0,0,148.6,149.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(8).to({_off:false,startPosition:9},0).wait(31));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-32.5,-324.9,44,40);


(lib.Headline = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(1));

	// Text (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AHiHPQgQgNAAgTQAAgYAUgbQARgXApgjIAHg6QgXAhgeAAIAAAAQgRAAgNgKQgRgMgCgZQgLAPgOAOQgYAYgcAAQgdAAAAhCQgPAbgUAXQgXAZgYAAQggAAgNgSQgOgSAAgrIAAgBQgMAUgQASQghAkgegCQgUAAgRgQQgRgQAAgzQAAgVAEgaQAGgZANgSQANgTAXAAQAKAAAKAGQAJAEABAQQAAAZgOAQQgMANgQABIgBAdQAAAsAOAAQAQAAAagXQAbgYARgeIACgDIAGgyQAKhAAUhiIADgDQADgCAFAAQAHAAALAFQANAHAAArQAAAagEAmIgNBnQgGAjABAWQgBAdAKAAQAJABAZgeQAageANgbIADgFQADgXAFgaQAAgHAIgEQAHgFAJAAQAQAAAAAQIAAAwQAABGAGAAQAEAAANgRIAlgsQAHgZAOgQQAbgdAqAAQAMAAALAFQADgXACgDQAHgHAJAAQALAAAHAJQAIAJAAAQIgCA5QgDArgEAnQA2gyAUgmQAEgsAFglQAJhBAKgeQAAgFAGgEQAFgEAHAAQAUAAAAATIgDBFQgDA7gFA1QARgXATAAQAeAAALAPQALAQAAAXIgDApQAAAFACAAQANAAASgTQARgSAQgaIARgZIABgBIAGhgQgmgDgPgIQgEgDgCgDIAAgEIACgIQADgGABAAIADgBIA0AJQAGhWAIAAQALgEAJAAQAbAAAAAjQgBAJgDARIgEAhIAtgCIAMgCQAKAAAAAJQAAAKgEAAQgXAHgrABQgEAxgBBqIgCBXQgCARgJALQgIAKgNAAQgJAAgIgHQgFgGAAg/IABg3QgMAVgQASQgWAWgdAAQg0AAAAg7IACgiQAAgFgCAAQgIAAgLAOQgMAQgJASQgKBQgLAHQgRAPgLAAQgMAAAAgWQgBgaAGhBQgIANgJAMQgXAcgjAbQgKBHgSAvQgRAugbAAQgcAAgRgOgAH3GwQAAAIACACQACACAHAAQALAAANhSQgjAgAAAmgAH7C+QgOAeABAXQAAAWANAAQAFAAAIgQQAJgSAFgTQAHgWAAgOQgBgPgHAAIgCAAQgLAAgNAdgABvCKQgEAJAAAMIgBAMQATgFAAgbQAAgIgFAAQgHAAgCAHgAinEVQgJghAAgaIAAgBQAAidAKguQgGgFAAgJIACgFIANgCQAFgFAIAAQAJAAAIAEQBAAAAwAaQAwAagBBJQAABMgVApQgWAqgeAOQgeAOggAAIgMAAQgHAGgMAAQgaAAgHghgAhlBIIABCbQAAAfgCAOQAdgEAPgVQAPgTAEgcQAFgWAAgnQAAgtgPghQgOghglAAIgFAAQAEATAAAZgAFnBZQgBgFAOgKQAPgKAHAAQAIAAAAALQAAAJgIAKQgHAKgIAAQgUAAAAgPgAC9geQAAAEgFgMQgDgOgFgoQgDgogChRIgIhqQgBgHAHgGQAGgFAJAAQAWAAAMAjQAOgXAVAAQA4AAAAA+QgBApgQAZQAWgQARgWQASgWALgUIAFgKQAIgTAPgOQAagbAZABQAGAAABACIAEAAQAKAAAKALQAMAPAAAaIAABBQABARADAAQANAAAnhAIAMgUQgMgPgFgKQgHgOAAgPQAAgJAEgNQAEgMAIAAIAKgCQANgDAGAAQAXAAAAAcQAAAhgKAcQAZApAAAhQAAAYgFASQgGARgIATQgHANAAAGQAAAKAGALIAAAEQAAAHgDAFIgGAEIgHABQgMAAgKgOQgKgMAAgkQAAgQAVgnQAQggAAgHQAAgNgJgPIAAABIgGgEIgEAIQgUAlgXAdQgWAdgVAAQgSAAgLgYQgMgYAAgrQgLAdgNASQgPASgLAAQgMAAgGgGQgFgGgCgRQgRAagVAMQgpAaglAAIgKAAIgCAAIAAALQAHAsABApQgBANgBAFQgCAJgIAHQgJAGgKAAQgKAAgHgGgADekRIAGBQQAWgOAHgTQAGgQABggQgBgRgDgGQgDgEgHAAQgQAAgMAcgAGkk4QgiAegBAnQABAMAEAAQAFAAAIgRQAKgRAKgXQAJgYACgIIABgDIgBAAQgBAAgNALgAIzlYQAAAHAFAKIABgYQAAgLgEAAQgCAAAAASgAgCipQgMgLAAgNQAAgPANAAQAHAAAFAKQAFANALAAQALAAAEgGQAEgHABgPQAAgNgUgmQgQgfgGgQQgGgWgBgTQAAgvAPgaQAQgaAWgKQAVgKASAAQASAAALAMQAHAIABAHQAAAFgEAEQgDAFgHAAQgCAAgGgGQgIgJgIAAQgMAAgJALQgJALAAAeQAAAXAEASQAGAZAVAiQALASAHAOQAFAOAAASQABAjgXATQgWASgmAAQgVAAgMgMgALZi2QgQgSgOgaIgEgIQgYBDgNAAQgTAAABglQAAgtAgh7IAFgNQADgQALgIQAKgIAMAAQAZAAAAAbQAAAGgIAeIgRBBQASgZAYgXQAWgXAKAAQADAAAFADQAGADAAAHQAAAGgeAdQgbAcgeAZQAOAKAPAYQAJAPAHAFQAHAHAJAAQAUAAARgPQARgQALgRIAMgUQAKgPAFAAIACACQADACABAHIgEAOQAAAEgMAYQgMAWgXAVQgYAUggAAQgWAAgPgRg");
	mask.setTransform(103.15,47.725);

	// Color_1
	this.instance = new lib.Color_1("synched",0);
	this.instance.setTransform(150,150,1,1.0001,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleY:1},0).to({scaleY:1.0001,alpha:0},10).wait(10).to({startPosition:0},0).to({scaleY:1,alpha:1},10).wait(1));

	// Color_2
	this.instance_1 = new lib.Color_2("synched",0);
	this.instance_1.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).wait(10).to({scaleY:1.0001},0).to({alpha:0},10).wait(11));

	// Color_3
	this.instance_2 = new lib.Color_3("synched",0);
	this.instance_2.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(21));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(85.5,0.6,120.80000000000001,94.9);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(1));

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AANAiIAAgkQAAgMgEgDQgCgCgGgBQgGAAgDAEQgEAEAAAOIAAAgIgQAAIAAhCIAQAAIAAAHQAHgIAKAAQANAAAHAJQAEAFAAAOIAAAng");
	this.shape.setTransform(152.825,18);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZAZQgKgJAAgQQAAgOAKgKQALgKAOAAQAPAAALAKQAKAKAAAOQAAAQgKAJQgLALgPAAQgOAAgLgLgAgNgPQgGAFAAAKQAAAKAFAFQAGAHAIgBQAJABAFgHQAGgFAAgKQAAgKgHgFQgFgGgIAAQgHAAgGAGg");
	this.shape_1.setTransform(144.75,18.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHA1IAAhDIAPAAIAABDgAgGgiQgDgDAAgEQAAgFADgDQADgDADAAQAEAAADADQADADAAAFQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape_2.setTransform(138.725,16.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAuIAAg0IgHAAIAAgPIAHAAIAAgYIAOAAIAAAYIAMAAIAAAPIgMAAIAAA0g");
	this.shape_3.setTransform(135.2,16.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZAYQgIgJAAgPQAAgPAJgKQAKgJANAAQAMAAAHAJIAAgIIAQAAIAABCIgQAAIAAgGQgHAIgMABQgPAAgJgMgAgMgOQgFAGAAAIQAAAJAFAGQAFAGAHAAQAIAAAGgFQAFgGAAgKQAAgJgFgGQgGgFgIgBQgHABgFAGg");
	this.shape_4.setTransform(128.725,18.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVAiIAAhCIAPAAIAAAHQADgFADgBQAEgCAGAAQAGAAAGACIgGAPQgEgDgFAAQgFAAgDAEQgFAFAAAKIAAAig");
	this.shape_5.setTransform(122.55,18);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgHA1IAAhDIAPAAIAABDgAgGgiQgDgDAAgEQAAgFADgDQADgDADAAQAEAAADADQADADAAAFQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape_6.setTransform(117.575,16.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghA1IAAhnIAPAAIAAAHQAIgJALAAQAOAAAJAKQAKAJAAAQQAAAQgKAKQgKAJgMAAQgMAAgIgKIAAAtgAgNggQgGAGAAAKQAAAKAGAGQAFAEAIAAQAIAAAFgFQAFgGAAgJQAAgJgFgGQgFgHgIAAQgIAAgFAGg");
	this.shape_7.setTransform(111.775,19.825);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgPAfQgGgFgCgHIANgGIADAHQADACAEAAQADAAADgCQACgDAAgDQAAgDgCgCIgGgEIgGgCQgGgDgDgDQgEgEAAgHQAAgJAFgFQAGgHAJABQAIgBAFAEQAFADADAFIgMAIQgDgGgHAAQgCAAgBACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAABQABAAABAAIADADIAIAEQAIAEACABQAFAFAAAIQAAAJgGAGQgHAIgLAAQgJAAgGgFg");
	this.shape_8.setTransform(104.55,18.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AANAiIAAgkQAAgMgEgDQgCgCgGgBQgGAAgDAEQgEAEAAAOIAAAgIgQAAIAAhCIAQAAIAAAHQAHgIAKAAQANAAAHAJQAEAFAAAOIAAAng");
	this.shape_9.setTransform(97.725,18);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgHA1IAAhDIAPAAIAABDgAgGgiQgDgDAAgEQAAgFADgDQADgDADAAQAEAAADADQADADAAAFQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape_10.setTransform(92.075,16.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVAiIAAhCIAQAAIAAAHQADgFACgBQAEgCAGAAQAGAAAGACIgHAPQgDgDgFAAQgFAAgDAEQgFAFABAKIAAAig");
	this.shape_11.setTransform(84.5,18);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVAbQgHgIAAgPIAAgmIAQAAIAAAmQAAAIADAEQADAFAGAAQAHAAADgFQADgEAAgIIAAgmIAQAAIAAAmQAAAPgHAIQgJAIgNAAQgNAAgIgIg");
	this.shape_12.setTransform(77.475,18.175);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYAZQgLgJAAgQQAAgOALgKQAKgKAOAAQAQAAAJAKQALAKAAAOQAAAQgLAJQgKALgPAAQgOAAgKgLgAgNgPQgGAFAAAKQAAAKAFAFQAFAHAJgBQAJABAFgHQAGgFAAgKQAAgKgHgFQgFgGgIAAQgIAAgFAGg");
	this.shape_13.setTransform(69.4,18.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggA0IAZgvIgeg4IAUAAIASAnIATgnIASAAIg1Bng");
	this.shape_14.setTransform(61.3,19.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgZAwQgIgKAAgOQAAgQAJgJQAKgKANAAQAMAAAHAKIAAg5IAQAAIAABzIgQAAIAAgHQgHAJgMAAQgPAAgJgLgAgMAJQgFAGAAAJQAAAJAFAGQAFAGAHAAQAIAAAGgFQAFgGAAgKQAAgKgFgGQgGgGgIAAQgHAAgFAHg");
	this.shape_15.setTransform(49.375,15.725);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AANAiIAAgkQAAgMgEgDQgCgCgGgBQgGAAgDAEQgEAEAAAOIAAAgIgQAAIAAhCIAQAAIAAAHQAHgIAKAAQANAAAHAJQAEAFAAAOIAAAng");
	this.shape_16.setTransform(41.425,18);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgHA1IAAhDIAPAAIAABDgAgGgiQgDgDAAgEQAAgFADgDQADgDADAAQAEAAADADQADADAAAFQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape_17.setTransform(35.775,16.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgaA1IAAhpIA1AAIAAAPIglAAIAAAbIAjAAIAAAOIgjAAIAAAxg");
	this.shape_18.setTransform(30.775,16.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(40));

	// Button (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AuVCgIA2igIg2ifIcrAAIg2CfIA2Cgg");
	mask.setTransform(91.825,16);

	// Color_1
	this.instance = new lib.Color_1("synched",0);
	this.instance.setTransform(150,150,1,1.0001,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleY:1},0).to({scaleY:1.0001,alpha:0},10).wait(10).to({startPosition:0},0).to({scaleY:1,alpha:1},10).wait(1));

	// Color_2
	this.instance_1 = new lib.Color_2("synched",0);
	this.instance_1.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).wait(10).to({scaleY:1.0001},0).to({alpha:0},10).wait(11));

	// Color_3
	this.instance_2 = new lib.Color_3("synched",0);
	this.instance_2.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(21));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,183.7,32);


(lib.Callout_Title = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(1));

	// Callout (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Am3EuIAAgnQgYgDgUgNIAAAAQgQgKgKgQIAAAAIAagbQAKAOAKAHIAAAAQAOAKASAAIAAAAQARAAAKgJIAAAAQAJgJAAgNIAAAAQAAgKgIgJIAAAAQgFgFgVgJIAAAAQgfgMgPgPIAAAAQgRgPAAgZIAAAAQAAgZAQgSIAAAAQAPgQAWgGIAAAAIAAgiIAdAAIAAAiQAOACAPAHIAAAAQAOAHAKALIAAAAIgXAeQgQgUgVAAIAAAAQgQAAgIAJIAAAAQgHAHAAAJIAAAAQAAAKAJAHIAAAAQAFAEAYAKIAAAAQAhAPAJAJIAAAAQASARAAAbIAAAAQAAAggVAUIAAAAQgQAQgXAEIAAAAIAAAogAAEDqQgigiAAg2IAAAAQAAg1AigjIAAAAQAjgiA3AAIAAAAQA3AAAjAiIAAAAQAiAjAAA1IAAAAQAAA2giAiIAAAAQgjAjg3AAIAAAAQg4AAgigjgAAlBYQgVAXAAAjIAAAAQAAAkAVAWIAAAAQAWAXAjAAIAAAAQAiAAAWgXIAAAAQAWgWAAgkIAAAAQAAgjgWgXIAAAAQgWgXgiAAIAAAAQgjAAgWAXgAkhECQgPgHgOgNIAAAAIAQgnQAKAOAOAHIAAAAQAQAJASAAIAAAAQAWAAAOgOIAAAAQAMgNAAgVIAAAAQAAgUgOgNIAAAAQgNgLgXAAIAAAAQgaAAgZAPIAAAAIAch7IBsAAIAAAnIhOAAIgIAlIAQgBQAlAAAXAXIAAAAQAVAVAAAjIAAAAQAAAmgYAXIAAAAQgYAZgoAAIAAAAQgfAAgUgLgAHPEEQgIgIAAgMIAAAAQAAgLAIgIIAAAAQAIgIALAAIAAAAQAMAAAIAIIAAAAQAIAIAAALIAAAAQAAAMgIAIIAAAAQgIAIgMAAIAAAAQgLAAgIgIgAFlEHIAAhzIgQAAIAAglIAQAAIAAgqQAAglAUgRIAAAAQAPgMAXAAIAAAAQANAAAMAFIAAAAIAAAnQgJgGgLAAIAAAAQgKAAgGAIIAAAAQgEAHAAATIAAAAIAAAkIAoAAIAAAlIgoAAIAABzgAD/EHIAAhzIgQAAIAAglIAQAAIAAgqQAAglAUgRIAAAAQAPgMAXAAIAAAAQANAAALAFIAAAAIAAAnQgIgGgLAAIAAAAQgKAAgGAIIAAAAQgEAHAAATIAAAAIAAAkIAnAAIAAAlIgnAAIAABzgAHNDAIAAijIArAAIAACjgAjehYQgigiAAg4IAAAAQAAg0AigjIAAAAQAjgkA5AAIAAAAQAfAAAXANIAAAAQAbANARAeIAAAAIgoAVQgJgTgSgJIAAAAQgPgHgSAAIAAAAQghAAgVAVIAAAAQgYAWAAAnIAAAAQAAAlAYAXIAAAAQAUAUAgAAIAAAAQAbAAATgPIAAAAQAQgMAGgXIAAAAIg9AAIAAgnIBsAAIAAACQAAA/gjAiIAAAAQgeAfg1AAIAAAAQg1AAgggggAAghOQgYgWAAglIAAAAQAAglAXgXIAAAAQAWgVAjAAIAAAAQAnAAAUAZIAAAAQASAVAAAnIAAAAIAAADIhxAAQAAAQAHAKIAAAAQAKAOAVAAIAAAAQAYAAALgUIAAAAIAoAGQgUAwg3AAIAAAAQgkAAgWgWgAB9ieQgDgOgKgJIAAAAQgKgHgNAAIAAAAQgNAAgJAIIAAAAQgLAIgDAOIAAAAIBIAAIAAAAgADGg9IAAh0IgRAAIAAgkIARAAIAAg0IArAAIAAA0IAeAAIAAAkIgeAAIAAB0g");
	mask.setTransform(-0.0162,1.9795);

	// Color_1
	this.instance = new lib.Color_1("synched",0);
	this.instance.setTransform(0,0,1,1.0001,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleY:1},0).to({scaleY:1.0001,alpha:0},10).wait(10).to({startPosition:0},0).to({scaleY:1,alpha:1},10).wait(1));

	// Color_2
	this.instance_1 = new lib.Color_2("synched",0);
	this.instance_1.setTransform(0,0,1,1,0,0,0,150,150);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).wait(10).to({scaleY:1.0001},0).to({alpha:0},10).wait(11));

	// Color_3
	this.instance_2 = new lib.Color_3("synched",0);
	this.instance_2.setTransform(0,0,1,1,0,0,0,150,150);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(21));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.2,-40.3,180.5,80.69999999999999);


(lib.Headline_Container = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Headline
	this.instance = new lib.Headline("synched",29);
	this.instance.setTransform(77.35,-375,0.42,0.42,0,0,0,136.9,38);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(29).to({_off:false},0).wait(11));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(23.6,-390.6,114.5,51.60000000000002);


(lib.CTA_Container = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// CTA
	this.instance = new lib.CTA("synched",9);
	this.instance.setTransform(94.85,-513.25,0.4054,0.4031,0,0,0,74.8,15.4);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).wait(31));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(64.6,-519.4,74.4,12.899999999999977);


(lib.Callout_Title_Container = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Callout_Title
	this.instance = new lib.Callout_Title("synched",9);
	this.instance.setTransform(94.85,24.2,0.495,0.4914,0,0,0,0.1,0.2);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).wait(10).to({startPosition:19},0).to({_off:true},1).wait(20));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(50.1,4.3,89.30000000000001,39.6);


// stage content:
(lib._320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,29,209];
	// timeline functions:
	this.frame_0 = function() {
		this.loops = 0;
	}
	this.frame_29 = function() {
		if (this.loops >= 3) {
			this.stop();
		} else {
			this.loops++;
		}
	}
	this.frame_209 = function() {
		this.gotoAndPlay(29);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(29).call(this.frame_29).wait(180).call(this.frame_209).wait(1));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A4/j+MAx/AAAIAAH9Mgx/AAAg");
	this.shape.setTransform(160,24.9883,1,0.9804);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(210));

	// Logo
	this.instance = new lib.Logo_Container("single",0);
	this.instance.setTransform(154.5,377.9,1,1,0,0,0,116.8,17.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({y:347.9,alpha:1},10,cjs.Ease.quadOut).wait(50).to({mode:"synched",startPosition:9,loop:false},0).wait(10).to({mode:"single",startPosition:19},0).wait(50).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:29},0).wait(50).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:39},0).wait(11));

	// Headline
	this.instance_1 = new lib.Headline_Container("single",29);
	this.instance_1.setTransform(149.95,464.55,1,1,0,0,0,136.2,38.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(139).to({_off:false},0).to({y:434.55,alpha:1},10,cjs.Ease.quadOut).wait(40).to({mode:"synched",loop:false},0).to({alpha:0,mode:"single",startPosition:39},10).wait(11));

	// Callout_Title
	this.instance_2 = new lib.Callout_Title_Container("single",9);
	this.instance_2.setTransform(110,42.2,1,1,0,0,0,110,12.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(14).to({_off:false},0).to({y:12.2,alpha:1},10,cjs.Ease.quadOut).wait(45).to({mode:"synched",loop:false},0).to({alpha:0,mode:"single",startPosition:19},10).wait(120).to({y:22.2,startPosition:9},0).to({y:12.2,alpha:1},10,cjs.Ease.quadOut).wait(1));

	// Callout_Body
	this.instance_3 = new lib.Callout_Body();
	this.instance_3.setTransform(150.25,240.45);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(79).to({_off:false},0).to({y:210.45,alpha:1},10,cjs.Ease.quadOut).wait(40).to({alpha:0},10,cjs.Ease.quadOut).wait(71));

	// CTA
	this.instance_4 = new lib.CTA_Container("single",9);
	this.instance_4.setTransform(150,584,1,1,0,0,0,74,16);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(19).to({_off:false},0).to({y:554,alpha:1},10,cjs.Ease.quadOut).wait(40).to({mode:"synched"},0).wait(10).to({mode:"single",startPosition:19},0).wait(50).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:29},0).wait(50).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:39},0).wait(11));

	// image1
	this.instance_5 = new lib.image1();
	this.instance_5.setTransform(233.6,55.25,1,1,0,0,0,75,58.7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(9).to({_off:false},0).to({alpha:1},10).wait(50).to({alpha:0},10).wait(110).to({alpha:1},10).wait(11));

	// Image_2
	this.instance_6 = new lib.Image_2();
	this.instance_6.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(69).to({_off:false},0).to({alpha:1},10).wait(50).to({alpha:0},10).wait(71));

	// Image_3
	this.instance_7 = new lib.Image_3();
	this.instance_7.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(129).to({_off:false},0).to({alpha:1},10).wait(50).to({alpha:0},10).wait(11));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(93,3.8,231.39999999999998,91.10000000000001);
// library properties:
lib.properties = {
	id: '3CBE87262503364BA85DD0BD72B2FD43',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/img_1.jpg", id:"img_1"},
		{src:"images/img_2.jpg", id:"img_2"},
		{src:"images/img_3.jpg", id:"img_3"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3CBE87262503364BA85DD0BD72B2FD43'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;