(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.img_1 = function() {
	this.initialize(img.img_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,720,616);


(lib.img_2 = function() {
	this.initialize(img.img_2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1940,500);


(lib.img_3 = function() {
	this.initialize(img.img_3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2160,394);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.image1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.img_1();
	this.instance.setTransform(165,0,0.233,0.233);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F7F8F3").s().p("EgmtAGCIAAsDMBNbAAAIAAMDg");
	this.shape.setTransform(-82.7,27.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image1, new cjs.Rectangle(-330.4,-11.2,663.2,154.7), null);


(lib.Image_3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.img_3();
	this.instance.setTransform(-137,-21,0.2803,0.2803);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Image_3, new cjs.Rectangle(-137,-21,605.4,110.4), null);


(lib.Image_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.instance = new lib.img_2();
	this.instance.setTransform(118,-21,0.1804,0.1804);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#AAD7F4").s().p("AzCFlIAArJMAmFAAAIAALJg");
	this.shape.setTransform(-3.9,27.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Image_2, new cjs.Rectangle(-125.8,-21,593.8,90.2), null);


(lib.Color_3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#152B52").s().p("A3bXcMAAAgu3MAu3AAAMAAAAu3g");
	this.shape.setTransform(149.9998,150,1.0001,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Color_3, new cjs.Rectangle(0,0,300,300), null);


(lib.Color_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0870B9").s().p("A3bXcMAAAgu3MAu3AAAMAAAAu3g");
	this.shape.setTransform(149.9998,150,1.0001,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Color_2, new cjs.Rectangle(0,0,300,300), null);


(lib.Color_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00919D").s().p("A3bXcMAAAgu3MAu3AAAMAAAAu3g");
	this.shape.setTransform(149.9998,150,1.0001,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Color_1, new cjs.Rectangle(0,0,300,300), null);


(lib.Callout_Body = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgCACQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIACgBIADABIABACIgBACIgDACQAAAAAAAAQAAAAAAAAQgBgBAAAAQAAAAgBgBg");
	this.shape.setTransform(38.9,-160.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgKAOQgFgGAAgIQAAgHAEgEQAFgGAGAAQAJAAAEAHQADAEAAAHIgZAAQAAAFADADQADADAEABQAEAAACgDQADgCABgCIAFACIgEAGQgFADgGAAQgGAAgFgDgAAKgCQgBgFgCgCQgDgDgEABQgCgBgDADQgDACgBAFIATAAIAAAAg");
	this.shape_1.setTransform(36.1281,-161.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLAJIAGgCQACAGADAAQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAAAIgEgDIgHgDQAAgBgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQABgFADgCQACgCADgBQAGAAAEAHIgGACQgBgEgDABQgDAAAAADQAAABAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAEACQAFACADACQACADAAADQgBAFgDADQgDACgFAAQgIAAgDgIg");
	this.shape_2.setTransform(32.85,-161.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgKANQgGgFAAgIQABgHAEgFQAFgEAGgBQAGABAFAFIAAgFIAGAAIAAAgIgGAAIAAgEQgFAFgGAAQgGAAgEgEgAgHgJQgCAEAAAFQgBAFADAEQADAEAEAAQAFgBAEgEQACgDAAgFQAAgFgDgEQgDgCgFAAQgEAAgDACg");
	this.shape_3.setTransform(29.2,-161.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAIAdIAAgUQAAgEgCgCQgCgDgDAAQgDAAgCADQgDADAAAGIAAARIgFAAIAAg5IAFAAIAAAcQAEgEAFAAQAGAAADAEQACADAAAGIAAAUg");
	this.shape_4.setTransform(25.325,-163.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgIANQgFgGAAgHQAAgHAFgEQAFgGAGAAQAGAAAFAEIAAAGQgEgEgHAAQgDgBgEAEQgDADAAAFQAAAGADADQAEAEADAAQAHAAAEgGIAAAHQgFADgGAAQgGAAgFgEg");
	this.shape_5.setTransform(21.7,-161.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgIARIAAggIAFAAIAAADQADgEAEAAIAFACIgDAEIgDgBQgDAAgBADQgCACAAAGIAAARg");
	this.shape_6.setTransform(19.075,-161.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgJANQgDgEAAgGIAAgTIAFAAIAAASQAAAFACADQACACADAAQAEAAACgCQABgDAAgFIAAgSIAGAAIAAATQAAAGgDAEQgEAEgGAAQgFAAgEgEg");
	this.shape_7.setTransform(15.775,-161.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgPAaIAAgyIAFAAIAAAEQAEgFAHAAQAHAAAEAFQAEAFABAHQgBAIgEADQgEAGgHAAQgGAAgFgGIAAAXgAgGgRQgEAEAAAFQAAAGADACQADAEAEAAQAFAAADgEQADgCAAgGQAAgFgDgEQgDgDgFAAQgDAAgDADg");
	this.shape_8.setTransform(11.9,-160.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgKAOQgFgGAAgIQAAgHAEgEQAFgGAGAAQAJAAAEAHQADAEAAAHIgZAAQAAAFADADQADADAEABQAEAAACgDQADgCABgCIAFACIgEAGQgFADgGAAQgGAAgFgDgAAKgCQgBgFgCgCQgDgDgEABQgCgBgDADQgDACgBAFIATAAIAAAAg");
	this.shape_9.setTransform(5.9781,-161.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgIARIAAggIAFAAIAAADQADgEAEAAIAFACIgDAEIgDgBQgDAAgBADQgCACAAAGIAAARg");
	this.shape_10.setTransform(3.175,-161.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgMANQgEgGAAgHQAAgHAEgEQAGgGAGAAQAIAAAEAGQAFAEABAHQgBAHgFAGQgEAEgIAAQgGAAgGgEgAgHgIQgEADAAAFQAAAGAEADQADAEAEAAQAFAAADgEQADgDABgGQgBgFgDgDQgDgEgFABQgEgBgDAEg");
	this.shape_11.setTransform(-0.35,-161.85);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgDAWIAAgaIgEAAIAAgGIAEAAIAAgMIAFAAIAAAMIAGAAIAAAGIgGAAIAAAag");
	this.shape_12.setTransform(-3.2,-162.45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgLAJIAGgCQACAGADAAQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQgBAAAAAAIgEgDIgHgDQAAgBgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAgFAEgCQACgCADgBQAGAAADAHIgEACQgCgEgDABQgDAAAAADQAAABAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAEACQAFACACACQADADAAADQAAAFgEADQgDACgFAAQgIAAgDgIg");
	this.shape_13.setTransform(-5.5,-161.85);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgIADIAAgFIARAAIAAAFg");
	this.shape_14.setTransform(-8.225,-161.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AAIARIAAgUQAAgDgCgCQgCgDgDAAQgDAAgCADQgDACAAAGIAAARIgFAAIAAggIAFAAIAAADQAEgEAFAAQAGAAADAEQACADAAAGIAAAUg");
	this.shape_15.setTransform(-11.375,-161.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgCAZIAAggIAFAAIAAAggAgCgRIgBgDIABgDQAAAAABAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgBgBAAAAg");
	this.shape_16.setTransform(-14.05,-162.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgDAWIAAgaIgEAAIAAgGIAEAAIAAgMIAFAAIAAAMIAGAAIAAAGIgGAAIAAAag");
	this.shape_17.setTransform(-17.5,-162.45);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AALAQIgLgNIgKANIgGAAIAOgRIgMgPIAHAAIAIAMIAIgMIAHAAIgMAQIANAQg");
	this.shape_18.setTransform(-20.25,-161.85);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgKAOQgFgGAAgIQAAgHAEgEQAFgGAGAAQAJAAAEAHQADAEAAAHIgZAAQAAAFADADQADADAEABQAEAAACgDIAEgEIAFACIgEAGQgFADgGAAQgGAAgFgDgAAKgCQgBgFgCgCQgDgDgEABQgCgBgDADQgDACgBAFIATAAIAAAAg");
	this.shape_19.setTransform(-23.9219,-161.85);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AAIARIAAgUQAAgDgCgCQgCgDgDAAQgDAAgCADQgDACAAAGIAAARIgFAAIAAggIAFAAIAAADQAEgEAFAAQAGAAADAEQACADAAAGIAAAUg");
	this.shape_20.setTransform(-27.725,-161.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgIARIAAggIAFAAIAAADQADgEAEAAIAFACIgDAEIgDgBQgDAAgBADQgCACAAAGIAAARg");
	this.shape_21.setTransform(-32.325,-161.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgJANQgDgEAAgGIAAgTIAFAAIAAASQAAAFACADQACACADAAQAEAAACgCQABgDAAgFIAAgSIAGAAIAAATQAAAGgDAEQgEAEgGAAQgFAAgEgEg");
	this.shape_22.setTransform(-35.625,-161.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgLANQgGgGAAgHQAAgHAGgEQAEgGAHAAQAHAAAFAGQAGAEgBAHQABAHgGAGQgFAEgHAAQgHAAgEgEgAgHgIQgEADABAFQgBAGAEADQADAEAEAAQAFAAADgEQAEgDgBgGQABgFgEgDQgDgEgFABQgEgBgDAEg");
	this.shape_23.setTransform(-39.55,-161.85);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgMAaIALgWIgQgdIAHAAIALAYIALgYIAGAAIgXAzg");
	this.shape_24.setTransform(-43.475,-160.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgEAdIAAgcIgEAAIAAgDIAEAAIAAgPQAAgHADgDQACgBAEAAIADAAIAAAFIgDAAQgBAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABIgBAEIAAAPIAIAAIAAADIgIAAIAAAcg");
	this.shape_25.setTransform(46.5,-171.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgFAdIAAgcIgDAAIAAgDIADAAIAAgPQAAgHAEgDQACgBAEAAIAEAAIAAAFIgEAAQgBAAgBAAQAAAAgBAAQAAABAAAAQgBAAAAABIgBAEIAAAPIAJAAIAAADIgJAAIAAAcg");
	this.shape_26.setTransform(44.6,-171.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgLANQgGgFAAgIQAAgHAGgFQAEgEAHAAQAHAAAFAEQAGAFAAAHQAAAIgGAFQgFAEgHAAQgHAAgEgEgAgHgIQgEADABAFQgBAGAEADQADADAEABQAFgBADgDQAEgDgBgGQABgFgEgDQgDgDgFgBQgEABgDADg");
	this.shape_27.setTransform(41.45,-170.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgMAXIgFgFIAFgEIAEAFQADADAFAAQAFAAAEgEQADgEAAgGQAAgGgDgCQgEgEgFAAQgFAAgFAEIAIgaIAUAAIAAAFIgSAAIgBAMIABAAQAJAAAEAFQAFAEAAAIQAAAJgGAFQgFAFgHAAQgHAAgFgEg");
	this.shape_28.setTransform(35.05,-171.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAAAiIAAgHQgGAAgFgEQgDgEgCgFIAGgCQABAFACACQADACAEABIAAgWQgGgBgDgDQgEgDAAgGQAAgFAEgEQADgEAGgBIAAgGIADAAIAAAGIAGADQAEACACADIgFAEIgDgFIgEgBIAAASQAHACADADQAEAEAAAFQAAAGgEAFQgDAEgHABIAAAHgAADAWQAEgBACgEIABgFQAAgEgCgDIgFgDgAgFgSQgCACAAADQAAADACACIAFADIAAgQQgEABgBACg");
	this.shape_29.setTransform(30.775,-171.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgKANQgFgEAAgJQAAgHAEgFQAFgEAGAAQAJAAAEAFQADAGAAAGIgZAAQAAAFADAEQADADAEAAQAEgBACgCQADgCABgDIAFADIgEAFQgFAEgGAAQgGAAgFgEgAAKgDQgBgDgCgDQgDgCgEgBQgCABgDACQgDADgBADIATAAIAAAAg");
	this.shape_30.setTransform(24.7781,-170.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgQgQIAHAAIAJAUIAKgUIAHAAIgRAig");
	this.shape_31.setTransform(21.2,-170);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgCAZIAAggIAFAAIAAAggAgCgRIgBgCIABgEQAAAAABAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgBgBAAAAg");
	this.shape_32.setTransform(18.7,-170.95);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgKANQgFgEAAgJQAAgHAEgFQAFgEAGAAQAJAAAEAFQADAGAAAGIgZAAQAAAFADAEQADADAEAAQAEgBACgCIAEgFIAFADIgEAFQgFAEgGAAQgGAAgFgEgAAKgDQgBgDgCgDQgDgCgEgBQgCABgDACQgDADgBADIATAAIAAAAg");
	this.shape_33.setTransform(15.9781,-170.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgIANQgFgFAAgIQAAgHAFgFQAFgEAHAAQAGAAAEADIAAAHQgEgGgGAAQgFABgCADQgEADAAAFQAAAGAEADQACADAFABQAGgBAEgFIAAAHQgEADgGAAQgHAAgFgEg");
	this.shape_34.setTransform(12.3,-170.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgKANQgFgEAAgJQAAgHAEgFQAFgEAGAAQAJAAAEAFQADAGAAAGIgZAAQAAAFADAEQADADAEAAQAEgBACgCQADgCABgDIAFADIgEAFQgFAEgGAAQgGAAgFgEgAAKgDQgBgDgCgDQgDgCgEgBQgCABgDACQgDADgBADIATAAIAAAAg");
	this.shape_35.setTransform(8.6781,-170.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgIARIAAggIAFAAIAAAEQADgFAEAAIAFABIgDAGIgDgBQgDAAgBACQgCACAAAGIAAARg");
	this.shape_36.setTransform(5.875,-170.15);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgLANQgGgFAAgIQAAgHAGgFQAEgEAHAAQAHAAAFAEQAGAFAAAHQAAAIgGAFQgFAEgHAAQgHAAgEgEgAgHgIQgEADABAFQgBAGAEADQADADAEABQAFgBADgDQAEgDgBgGQABgFgEgDQgDgDgFgBQgEABgDADg");
	this.shape_37.setTransform(0.5,-170.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgDAWIAAgbIgDAAIAAgEIADAAIAAgNIAFAAIAAANIAFAAIAAAEIgFAAIAAAbg");
	this.shape_38.setTransform(-2.35,-170.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgKAZQgGgFAAgIQABgIAEgEQAFgEAGAAQAGAAAFAEIAAgdIAGAAIAAA6IgGAAIAAgFQgFAGgGAAQgGAAgEgFgAgHADQgCADAAAGQAAAGACADQADAEAEAAQAFAAAEgEQACgEAAgFQAAgGgDgDQgEgDgEAAQgEAAgDADg");
	this.shape_39.setTransform(-7.35,-171.325);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgKANQgFgFgBgIQAAgIAFgEQAFgFAGABQAHgBAEAGIAAgEIAFAAIAAAfIgFAAIAAgEQgEAGgHgBQgGABgEgFgAgHgJQgDAEAAAFQABAFACAEQADADAEABQAFAAADgFQADgDAAgFQAAgFgEgEQgCgDgFAAQgDAAgEADg");
	this.shape_40.setTransform(-11.55,-170.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgLAJIAGgCQACAFADABQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAIgEgCIgHgFQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAgEAEgDQACgCADAAQAGAAADAFIgEADQgCgDgDgBQgDAAAAAFQAAAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAEACQAFADACABQADACAAADQAAAGgEACQgDADgFAAQgIABgDgJg");
	this.shape_41.setTransform(-16.75,-170.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgCAZIAAggIAFAAIAAAggAgCgRIgBgCIABgEQAAAAABAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgBgBAAAAg");
	this.shape_42.setTransform(-19,-170.95);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAIAdIAAgUQAAgEgCgCQgCgDgDAAQgDAAgCADQgDADAAAGIAAARIgFAAIAAg5IAFAAIAAAcQAEgEAFAAQAGAAADAEQACADAAAGIAAAUg");
	this.shape_43.setTransform(-21.725,-171.375);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgDAWIAAgbIgEAAIAAgEIAEAAIAAgNIAFAAIAAANIAGAAIAAAEIgGAAIAAAbg");
	this.shape_44.setTransform(-24.35,-170.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AAIARIAAgTQAAgFgCgBQgCgDgDAAQgDAAgCADQgDACAAAGIAAARIgFAAIAAggIAFAAIAAAEQAEgFAFAAQAGAAADAFQACACAAAHIAAATg");
	this.shape_45.setTransform(-29.025,-170.15);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgMANQgEgFgBgIQABgHAEgFQAFgEAHAAQAHAAAGAEQAEAFAAAHQAAAIgEAFQgGAEgHAAQgHAAgFgEgAgHgIQgDADgBAFQABAGADADQADADAEABQAFgBADgDQAEgDAAgGQAAgFgEgDQgDgDgFgBQgEABgDADg");
	this.shape_46.setTransform(-32.95,-170.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgCAZIAAggIAEAAIAAAggAgCgRIgBgCIABgEQAAAAABAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgBgBAAAAg");
	this.shape_47.setTransform(-35.85,-170.95);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgDAWIAAgbIgDAAIAAgEIADAAIAAgNIAFAAIAAANIAFAAIAAAEIgFAAIAAAbg");
	this.shape_48.setTransform(-37.45,-170.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AAIARIAAgTQAAgFgCgBQgCgDgDAAQgDAAgCADQgDACAAAGIAAARIgFAAIAAggIAFAAIAAAEQAEgFAFAAQAGAAADAFQACACAAAHIAAATg");
	this.shape_49.setTransform(-40.275,-170.15);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgKANQgFgEAAgJQAAgHAEgFQAFgEAGAAQAJAAAEAFQADAGAAAGIgZAAQAAAFADAEQADADAEAAQAEgBACgCIAEgFIAFADIgEAFQgFAEgGAAQgGAAgFgEgAAKgDQgBgDgCgDQgDgCgEgBQgCABgDACQgDADgBADIATAAIAAAAg");
	this.shape_50.setTransform(-44.0219,-170.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AgRgJIgFAkIgGAAIAJg3IATAsIAVgsIAIA3IgGAAIgFgkIgSAmg");
	this.shape_51.setTransform(-49.425,-171.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Callout_Body, new cjs.Rectangle(-58.6,-178.3,111.7,22.5), null);


(lib.Logo_Stacked = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(1));

	// Paper_Souce
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AqpCYIgIAAIgDgDQgFgDgHgCQgFgCgLACQgJABgGgDQgGgFAAgSQgBgMADgOQABgDgCgEQgBgKAIgGQADgCACABQAIAFACAFIgCAeQABAHAGAFQAKgBAQAEIAZAFQAMABALgDIAGAAQAkgJAJgWIACgLIAAgFQACgSgGgPIgFgEQgNgLgTgHIgHgBIgqgKQgZgGgNgIQgOgIgJgPQgNghAIgjQAKgZAVgRIAJgEIAGgEIAHgCIAHgDIAKgDIALgBQAHAAACgCIAKAAQAKgBAKABIAfAJIAEAAQAOADAJALQADAFgCAOIgCAUIgFAFQgQAAAAgJIgCgFIgBgEQgEgGgGgEIgDgBIgFgFQgNgFgMgCIgFABQgcgGgYARIgCAEIgFAEQgEAIgDAKIgGAOIgDAEQgBACABADQADAGAFAFQAKAKANAHIAdAMIAFAAIAPAEIAIABIALAEQADABAEAAIAFAFIAGADQADACALABQAJABADACQAJAGADAKIgBAIQgBAFACADIAHAIQAFAGACAEQACAEgCANIgDAQQgGAQgIANQgSAYgyAQIgIABIgJABIgQABQgKAAgKgCgAmNCYIgGAAIgOgDIgIgDIgFgBIgGgGQgDgFgCgBQgDgCgEABIgHAAIgKgEIgIgJIgFgDIgHgKIgFgEIgEgHIgKgOQgFgJgDgNIgFgKIgCgKIAAgGQgJgiAJglQAAgGACgDIAIgVIAFgOIAPgPIAKgHIAJgOIADgBIACgEIAHgEQAPgKAPgFQAKgEAWgFIAFAAIARgCQAigBAfALQAJACAGADQAHAGAFAPIAHAHIAKgCQAFgBAEABIAHAGQAJAJAGAKIABAFQAKAUAGAcIAAARQADASgEAQIgBAIQAAAFgBAEQgEAPgHARIgDAEIgKARIgGAGIgBACIgCABIgCAEIgRARIgCAAIgFAFIgEABIgDAEQgDABgGgBQgGAAgDABQgBABgDAGQgDAEgJAGIgDAAIgGADIgDAAQgUAGgVAAQgMAAgMgCgAmjh4QghASgMAjIgDAMIgFASQgBADABAEQACADgBACIgFAQIACADIAAAFIACAEQADAJADATIADALIACAKQAJAWALAQIAKAKIAAACIAIAGIADAEIACAAIAHAFIAFABIAFADQARAIAUgBIAKAAQAegIARgMQAQgNANgZQACgEACgIIADgMQAGgHABgDIABAAQABgDgCgEIgDgGQgBgNABgMQAAgTgDgRIgBgLQgGgYgQgTQgQgTgXgKQgLgDgRgEIgGAAIgRgCQgCABgHABIgDACIgDAAgAhuCVIgHAAIgDgCIgDAAIgEgEIgIgHQgIABgIgCQgKgFgJgPQgIgNgFgPIAAgOQgCgGAAgEQACgJgCgIIABgNQAAgGgBgHIAAgFQgBgHABgIIgBgLQABgHAAgJIgBgQIAAgKQABgKgBgIIgBgTQgBgEACgEIgBgQQgEgKgKgCIgJgBQgGgBgBgDQgCgBABgEIABgGIAGgEQAOgBAPADIAlgBIAdAAQAIAEAAAIIgDAEQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIgIABQgHABgFAFQgFAJgBALIAAAVIgBALQgBAEgFAGQgBAMACAPIgCAHIABAFQgBAIABAJIADAMIAEAKIAAALIAAAPIAEAiIAKAVIADAIQABAEADACQABAAAAAAQABABAAAAQABAAABgBQAAAAABAAIAFAAIASAGIAGAAIAYAAQALACAKgCIAJAAQALgDAJgEQASgLALgkQABgEABgIIABgNIAAhkQABgPgBgPQAAgEACgDQABgLgCgHQgDgJgJgFIgOgDQgHgCAAgKIAGgEIAJAAIAXABQARABAHgBIAIAAIAKAAIAOAAIADgBQAIgBAIABQADABAEgCQAEgBAHACIAVAAQACABAJgBQAaAEATATQAFAFADAEQAFALACAMIAAAJIABAEQAAAHgBAGIgCAIIgIAGQgGAEgBADQgCAEACADQACAEgBACQgBAGgDAEIgMAMIgOAGQgLAHgFACIgHAEQgEADAAAFIADAGIADACIADAGQACADAGAFIAoAtIAJAIIAJALIAGAGIAKAMQAPAHAIACIAEADIACAEIAAAHIgBAAQgCACgGgBIgJAAQgXABgVgBIgIgHQgFgEgCgDIgHgNIgBgGIgFgGIAAgBQgGgIgGgEIgKgEQgEgDgDgGIgFgDIgGgIIgDgCIgLgMIgDgEIgDgCIgFgHIgFgDIgFgHQgGgEgCgEQgDgHADgHIAKgIQAYgHAZgNIADgEQAEgCABgCQAIgLADgNQACgGAAgIQABgPgDgMQgHgXgmgQQgJgEgPAAQgQgBgHAFQgDADAAAEIAAAKIAAAMQABAIgBAEQgBADABAEIAAAKQgCATABAZQABAHgBAGIAAAVIAAAtQgBAEABAHIgFANQgBANAFAMIACAPQADAIASADQARADAAAKIgBACIgIAGQgWgBgTgFQgHAAgJACIgCACQgGAAgEgCIgGgCQgCgBgBgFIgBgGQgDgBgDABIgFADIgbANQgMAEgKACIgGAAQgMABgMAAQgSAAgTgEgAFwCXQgtgGgegWIgJgIQgGgFgGgGIgDgJIgHgGIgIgHQgFgHgBgGIgFgJQgEgIAAgHQgMgnAJgoIADgQIADgIQAIgHABgEIACgJIACgBIAEgJQABgFABgCQAGgEABgCIARgSIAIgEQAXgQAbgHIAOgDIAPgDIAFABIAFgBQAggCAkAJIAUAFIANAEQAIACADAFQAEAHgCAPIgGAYIgEADQgKAAgCgEIgDgJQgDgLgIgHQgdgTgsACQgsACgbAVIgFAIIgKAOIgDAHIgCACIgDAKIgIAWQgBAFgGAKIgBAEIgEAFQgCADAAADIAEAGIAEADIADADQABAGAAAMQACAMAFARIAFAHIAGAOIAHAJIAEAEIACAFQACADAGAEQAIAJALAHQATAJAWAGQAEABAJAAQAPAEAPgBQADgBAGABIAEgDIAFAAIAFgBIAIAAIAHgBIAGgHQALgKAPAAIADACQABAKgIAJQgHAHgLAEIgSAFQgcAKgeAAQgOAAgPgCgAKfCTIgPAAQgIAAgHgCIgSAAIgHgEIgJgCQgEgCgMAGIgKACIgPABQgKACgLgCQgNgCgDgGIAAgCQABgEAFgEIAIgGQAKgNAEgRIAAgJQACgUgCgVQgCgRADgSIAAgMQADgFABgDQABgFgDgJQgDgKAAgFIAAgeQACgRgDgPIgCgLQgBgGgDgCQgDgCgFgBIgKgBQgHAAgFgFQgBgIAHgGIAAABIAvAAIAtAAQAcgCATABQAGABAJgBIAKAAIAMAAQAAAAABAAQABABAAAAQABAAAAgBQABAAAAAAIAMAAIALACQAGACABADQAFAHgGAXIAAAFQABADgBACIgEAEIgEADIgLgBIgCgEIgFgNQgDgHgJAAQgDgCgKAAIgQgBQgagEgaAEIgHAAIgGABQgGAEgBAFQAEAIABAKIAAAJQABAHAAASQAAASACAIIAAAGQgBADABADQABAEAHADIALgBQASABAMgCIAXAAIAEgDQAKgEAAgGQACgDgBgIIACgGQAFgDADAAQAIAHACADQACAFgBAKIgBAOIAAA3IgEAFIgGABQgDAAgCgBQgDgDgBgEIgCgJQABgJgCgDQgFgJgQgDQgOgCgRACIgPAAQgJgBgDACQgDABgCAEQgCADAAAEIAAAGIAAALQgBAIABAFQABAFgCAPIgBASIAAAGIgBAGQADAKAIAHQAHAAAJABIAJAAQAGgBADABIAMgBQAMADALgDIAOAAQAKAAAKgEQAGgEACgJIAEgQIADgKQADgFAGAAIAEAEIAEAEQABAMgEAMQgBAIACAGQABALgDAKIgEAEIgIABIgDABIgDAAQgJABgGAAIgIAAIgPABIgPgBg");
	this.shape.setTransform(74.6281,119.4399);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AJdCWQgJABgIgBIgDgBQgOACgPgBQgPgIgKgPIgFgFIgFgHIgEgDQgCgMgDgFQgCgCgFgCQgFgDgCgCQgJgMgIgIIgGgDIgDgFIgNgMQgFgJgDgJIAAgDQgBgDgGgCQgGgCgCgDIgBgGIAGgDIAJAAIAegEQAcgNAMgdQACgEAAgIQAIgLADgIIAAgFIgBgDQgPgIgKgPIgEgHIgEgCIgEgFQgGgDgGgCIgIAAQgJgCgPABQgQABgGAFIgEAGIAAAdQACAHgCAHQgBAMABAMQABACgCADIABANQACAGgCAFIAAAIQABAEgBAGIAAAKIAAAOQACAPgCAPIAAAHQgBAKABALQACAMgCAYIAKAHQAFABALABQAJABAAAGQACAEgCAEQgIAFgKgBIgHgBQgHACgJgCIgJgDQgGgCgEABIgIADQgDABgEgBIgHgBQgSAFgSgFQgDgFACgGIAKgFIAFAAIALgDQAGgCACgDQAEgFACgRQABgPAAgIQACgNgBgDQgDgJgBgLIAAgVQAAgOABgHIAAgFIABgOIAAgYIAAgGIABgUIAEgFQADgDAAgFQgFgEgCgGQgCgDABgKQAAgIgCgEQgHgHgIgBIgLAAIgHgCQgDgEAAgFIADgGIAEgDQANAAAJADQAHABAGgBIADAAIAOAAQAMgCAQACQAFABAMgBIAHAEIAGADQACABAIgFIADAAQAFABAGgCIAFABIAIgDQAEgDAEABIAQADIACABIAEAAIAMAIIAEABQAQAKAIATQAGAOgBAPIAAAGQgFAVgEALQgJATgRALIgMAKIgMAHQgJABgCADQgDADAAAFQABACAEADIAEAHIAMAKIADADIAAABIAGAEIAFAEIAJANIAEAKQABACAFABIAKALIANARIACAEIAEAEQAFAGALAEIAKABQAOAFABAEIAAACIgIAIIgFABIgFgBgAEYCWIgKgBQgHACgHgCIgDAAQgOACgMgDIgFABQgKAAgMgBIg2AAQgRABgQgBQgHABgDgBIgFgFIAAgGIAFgGIAHgDIACAAQAMgFAHgLQACgLgBgIIAAgNQABgFgBgEQgBgJAAgHQACgOgBgSIgBgGQgBgRACgIQABgSgBgTIABgEIAAgJIACgGQACgJgEgLIAAgOIABgFQAAgFgBgFQgEgKgJgCIgGAAQgJgBgDgCQgGgCAAgGIAFgIIAFgBIAFgCIARADIAFAAIALABQAFAAAEADQACABADAHIAHAHIABAAIAFgCIAFgIQADgGADgBQACgBAEABIAIAAIAGgCQAEABADgBIASgBIAJAAQAKgBAJABQAEABALgBIAJAAQAKAAAIAEIADAEQAGAFAEAJQADAYgEAWIgCACQgDADgHAAIgEgDQgCgCgBgDIAAgEQAAgTgFgGQgDgFgHgBIgOgCQgOgEgYABIglADIgEADQgCACAAAEQgCANACANQgBACABAHIAAAKIAAAIIgBAFIAAARQgBAIACAGQADAFAGAAQADADAMgCQAOADATgCQAUgCAGgGQACgCACgLQACgJAGAAQABgBAFABIAFAGQADARgEAQIgFAGQgDADgBAFQgBADACADIADAFQAHAJAAAKIgHAHIgHAAQgGgEgBgDIgBgJQgCgIgFgHQgIgEgIAAQgdgCgdACIgHAIIgBAVQgIAfACASQADAbAWAGIAFAAQAOABATgBIAHAAQAOABANgDIAIAAIANgEQAEgCADgHIAEgWQAEgOAIAAIAGADQACABAAAEQgDAEABALQABANgBAFQgBAFgDAGIgDACIgCACIgBAHQgBAEgDADQgGAEgHADIgDAAIgHAAgAiTCSIgJAAIgIAAQgGABgGgCIgEABIgMgBIgMAAQgTACgUgCQgDgFAAgCQAAgCADgEIADgDQADgCAIgBQAIgBACgDQAGgKgEgMQgCgKgEgIQgEgFgCgHIgEgLIgKgIIhkAAIgNARIgGALQgHAHgFAJQgCALADAMQAFAEAIAEIANACQAHACAAAIIgFAHQgMACgSgCQgIABgEgBIgCgBQgGACgEgBQgFgBgMABIgSAAIgFgIIAAgEQAEgGAIgDIAHgBQAJgGAGgIIAEgJIAIgOQACgDAAgFIADgDIAAgDIADgDIABgGQAXgvAfhJIADgEIACgGIAOgeIAKgJQAHgGABgDQACgDgCgGQgDgHABgEQABgGAEgGIAEgDQAMAAAFAGQACAEAEAMIASArIARAnIAFAPQAPAgAcBGIANAiQAKASAPAFQAHABAJgCIAFABQALgCAGgIQABgDAAgHIAAgKQADgZgDgZQAAgPACgOQABgHgBgHIABgLIAAgKIABgMIgBgGIACgMIAAgFQgBgFABgDQADgIgDgIIgCgFIAAgIQABgJgBgJIAAgHQgDgKgMgEIgNgBQgIAAgBgGQgBgCABgFQAEgEAEgCQAEgBAJACIAUABIAJAAQAGgBADABQAFACAEgBIAOgBIADABIAbgBQAcgGAdAJIALACIADADQAHAFALALIAIAFIAEABIAEABQAFAGADAFIAAABQAHAbgGAaIgBAHQgBADgGAEQgFAFgCAEQgDAEgEAKQgEALgDADQgIAHgKAEIgNAGQgGACgHAAQgUAFgZgEIgBgCIAAgDIADgDQACgBAIgBIAKgCQAYgKAQgUIADgDQAFgJACgIIAAgHQAGgKABgGQABgDgDgHIgFgJQgCgHgFgMQgNgPgRgFIgHgBQgSgFgTAFIgFAAQgJACgHAAIgEAEQAAAGADAJQAEAKAAAHIAAAqQgCANACAMQABAJgBAIQgBAIACAGIAAAUQgCAQACAPIAAAVIAAAJQgBANACAMQAFAEAJAEIADgBIAJABQAFABACADQACAFgBAGQgJAGgOgEQgVgFgEAAIgIAAQgHACgGgBQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBAAAAAAIgbAGIgPABIgMgBgAlCgHIgGAMQAAAEgCACIgDAFQgCAEAAAEIADACQACABAHgBIAKAAQAFABAFgBIAwAAIAEgDQAAgIgEgIIgBgEIgEgEIgCgJIgPgjQgGgQgIgOIgDAAIgcBEgApKCQIghAAQgCgEgBgFQADgGAHgCIARgDQAKgDAAgJQABgBgBgEIAAgHQACgMgBgIIAAgIIAAgKQABgGgBgNQAAgNABgGIAAgPQABgSABgGQAEgJgBgJIgFgQIAAgHIAAgMQgBgIABgLQgBgGABgFQACgMgDgKQgGgIgLgCIgIAAIgJgDQgCgDgBgGIAIgHIAAgBIAWACIAWABQATgBAOABIAJAAQAFACAMAAQAMACAMgFIAKAAIAKAAIAMABQAIABAEABQAlANALAVQAEALACAMQABATgFAQIgDANIgGALIgCAFQgUAZgeANIgFAAIgGADIgRADQgHACgJgBQgFABgGgCQgGgCgBgDQgCgCABgFIAIgGQAJgCAJACQALABALgBQACgCADAAQAAgBABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAIgHQALgRAGgUIAAgEIABgEIgDghQgFgSgOgMQgDAAgCgCQgIgEgOgDQgSgEgUAGIgGACQgHAFgBAHIgCARQACAGgBAJIAAAFQABAFgBADQgCAKAAANIAAAMQgCANAEAOIAABIIAAANQgBALACAJIAAAGQgBADABACQADAHARAGIAKABQADABADAEIAAAHIgEADIgFABQgEACgKgCIgOgEIgJADIgNABQgIABgGgBIgDABIgDAAIgGAAg");
	this.shape_1.setTransform(75.025,15.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(40));

	// Wasp (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AAYFRIAAgDIgBgFIAAgMIgCgGQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAIABgDIgBgHIABgBIgDgCIAAgCQgDgFAAgCIAAgGIgEgDIgBgCIgEgDIgBgDIgEgCQgEgGgCgCQgHgCgBgCQgBgGgCgCIgFgDIgDgDIAAgEQgBgJgGgJIgEgCQgIgHgEgGQgCgHAGgBQAIAAAAgBQAAgBgFgCIgEgCQgCgBAAgEIAAgEIABAAIAAgCIAAgGIACgFQgCgDABgDIACgDIAAABIABAAIAAgCIgBAAIADgFQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAIAAgFQABgBABAAQAAAAABgBQAAAAABAAQAAgBAAAAIABgEIAEgFIACgEIAFgHIADAAIADgDIAKgJIAGgDIAEgEQAEgCAEgEIABgFIAEgEIgCgGIAAgDIgFgMIgBgHIgCgGQgCgDgEABIgCADIgDAAIgGADIgLAAIgHgDIgKABQgHgDgGAAIgGAEIgFABIgDAGIgGAFIgDABQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIgGALQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAIgEABIAAAFQgBADgDACQgEADgDgCIgEgGIgBAAIgCAGIgBADQgCABgEgBQgFAEgDAGIgBAPIAEAFQACAEgBADIgDADIgDACIgDgBQgBAAAAABQgBAAAAABQAAAAAAABQAAABABAAIABAGIgDAHQgEABgCAAQgIgKAGgLIAGgDIADgIIgEgDQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAABAAAAQAAAAAAABQAAAAAAAAQACAEAAADIgCABQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAQgCAAgFAIQgNACAEAGIABAAIAGgFQAFACABAEIAAAFIACADIgBAEIABAGQABADgCADIgHAAQgFgBgCABIgDAGIgGACIgCADIgBAEIgDADIAAAFIgCAFIgBAFIgEAEIgCAGIgOALQgCABgHABIAAAFQgDAIgFAFIgDABIgDAEIgFADIgGALIgJALQgCADABAIIgCAKQAAADADAEQABACgCAEIAFAHIACACIABADQAJACABAFQgDADgGAAIgBAEQgGABgHgEQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAQgJgBgJgFQAAgEgEgCQgCgBgDABIgFAAQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAgBIgCABQgEgFgBgFIAAgFIgDgCIgCgIIAFAAQACABACADQAFACAIgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAAgFIADgFIABgGIAAgEIADgDQgBgHAGgGIAJgKIABgEIADgCIACgFQAGgGAIgBQACgEAEgBQAFAAABgCQABgCAAgDQgCgFABgCIAFgMQAJgIAEgFIAIgKIAIgDQABgBACgEIABgEIAGgDQACgGgFgEQAAgMAKgFIAFgFQAEAAACgCIAFgFQADgIADgCQAQgJAHgGIADgEIAEgDIACgFIAGgDIAIgJIAEgCIACgEIAEgCIABgDIAEgDIAHgEQAEgDAEAAIAEACIABADIADABIACgBQAAgKAEgCQAJAAADgCIABgCIAGgCIACgCQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQANAAAHgBQACgFgBgFIgCgJIAAgDIAAgDIAAgGIgEgMIgCgLIgFgFQgBgGgEgCIgEABQgDALgDAXIgFAMQgBAHgEAGIgKAGQgEAFgDABIgVAFIgFgBIgHABIgMAAIgLgBIgGACIgHAAQgIADgGABIgIABIgLAGIgMADIgGAFIgFACIgHAFIgFAAIgFACIgIAAIgbAFQgHABgGgBIgGAAQgIgBgGgDIgGgGIgDgBIgBgEIgDgDIgDgVIgJACIgFADQgGAAgFgCQgDABgEgBIgOgEIgFABQgIgBgGgEIAAgGQABgFgBgCIgDgEQgFAAgDADIgGgCIgFABIgGABIgKgDQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAIgEABIgDgDIgCgBIgEgEQgFgCgCgCIgCgEQAAgEgCgBQgEgDgEADIABAFIAAADQgEABgDgCIgEgFIgHgGIgFgHIgEgCIgBgFIgDgCIgFgHQgGgDgBgCIgBgGIACgEIADgKQgDgJABgEIACgCIADgDQAEgJACgCIAEgDQAEgCABAAIACADQAAAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAFgDAFABIAEABQACAAADgEIALgCQAEgBAEACIABAAQAJgFADADIADAAIACADQAAAAABABQAAAAAAABQAAAAABAAQAAAAABAAIANAAQACABACAFIAEgCQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIgEAEIAAABQADgBACgEQADAAADgCIAFAAIACgBQAGgBAIADIAJgBIAIACQAGACADgBIAEgCIAGADIAKABIAEADIAHAAIAKACIAFgBIAOAHQAGgBAEgEIAEgDIAUgCIAEADIAFABIAEgCIAPAAIAFgCQAEgCABABIAJADQAEABAEgBIAMgBQAIgBgBgDIgSgHIgPAEIgEgBIgQABQgJACgJgBIgDgCIgGAAIgHgCIgIgCIgEgFQgCgDgEgBQgDACAAADIAAAFIgDAAIgEgDIgGgEIgFgGIgCgBIgIgFIgEgBQgFgEgFgCIgDAAIgEgBIgFABIgDgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAIgDABIgDgDIgHgCQgGAGgKgCIgCAAQgEgDgCACIgFADIgGAEIgCADQgDAEgGgHQACgIADgIQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIgBgEIAAgKIgCgGQAAgCAEgEIADAAQgBgEADgBQAEgBABADIACADQAAABAAAAQAAABABAAQAAABAAABQAAAAAAABIAAALQADAGADACQAFAEAHAAIAFgBIACABQAAAAABAAQAAAAAAAAQABAAAAgBQABAAAAAAQAFgBAGACIADgBIAEgBIABACIACAAIADgEQAGAAAEADIAIAFIAMAFIADADIAEABIAFAGIAGABIAEADQADABAEgCIAFgDQADAAAFACIAEgBIAFAAQAEABAGAEQACABADgBIAEADIAJACIAHADQADAAAGgDIAIAAIAJgCIAFABIAEgCIAHABIAFgBIAGADQADAAAFgDQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQACABAEgCQAEgBAEAEIAHAAIAEAAIAEAAIADgCIASABIAFACIAHgBIAHAAIABgBQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAIgCgDIgCgHIgFgEQgEgIgBgFIAAgIIgCgDIgCgMQABgDAFgBIAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAQgBAAAAAAQgEACgFAAIgGgJQgBgFgCgDIgHgHIgDgHIgFgGIgCgGIgGgEIgEgFQgEAAgDAFIgFAEIgDAFQgBACgFABIgHABQgEADgDAAQgDgCgBgFQgBgEADgEIAKgKQAHgHgCgHIgGgHIgCgGIAAgEIgDgFIgEgMQgBgDADgFQADgFADABQADAAAAAKQABAKADACIAGgFQADABAFAFIAFAIIADAHIACAAIACgIQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQABAAABAAQAAAAABAAQAAgBABAAQAAAAABAAIADgEIAFgDIAFgDIAHgCIADgCIALAAQABgEAEgBIAHAAQAGgCAIABIAIABIAMAGIAEABQADACADANIAAAFIAEAGIAFAMIAAAFIABADIABAHIgBAHQgBAHACAIIACACIAEAEIABABIACABQABgBACgIIAEgGIAAgCIADgMQgBgHABgCQABgCAHgDQgBgCABgDIADgFIAAgFIABgDIABgHQAEgKAHgJIADgGIAGgCIAEgDIAegBIAEABQAEABAJgBIAJAEIAEAAIAEADIAGADIAEAAQADgBADABQACABACAEIAHADQAEAEAGADIAFACIAEAFIACADQAFAFADABIACACIADABQAEgCACABIAEAEIACADIAAAFIADADIAEAIIADACQABAMgEAKIgFAFIgBADQgCAFgFACQAAABgBAAQAAAAgBAAQAAAAAAAAQgBAAAAgBIgDgDIgEgCQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAIADgGIABgFIADgEIABgFIAAgFIADAAIAEADIACAAIABgBQgCgFgDgBIgIgBIgFgDIgEgBQgEgFAAgHIgEgBIgFADIgEAAIgKACIgGAFIgFACQgCABgBAEIgCAHIgHALIAAAEIgCAGIgDACIgDAHQgCAEgDABIgFADIgDADIgFACIAAAHIgBADIAAAGIgFAFIgEAKIgDAEIAAADIgIAKIgGADQgEACgDAFQgDAFABADIABACQAEABADgFIACAAIADAAIAHAAIALgFIAEABQABAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIAFgDIAKAAQAGgDAMgBQAFABAJAFQAEABADgFIANAAIADgBIAEAAIAJgFIAJgBIAJgFIACAAQAFAAAFgBIAGgFIAEAAIADAAIAHgEIAHgDQAIgCAIgBIAHgEQALgCAKAAIAGAAIACgCIAEgBIAEABIAEABQADgBACgEIAPAAQAJAAACgEIAAgFIADgJIADgBIABgGIAFgIQADgBACABQAGACAAAFIAAAKQABAGgBAFIgHAIIgIgDQgDAGgDABIgDAAIgIACIgGAAIgCACIgCACQgKgBgFACQgEAEgCAAQgIgBgCABQgDACgBAHQAAAHgEABIgKgBIgDgDIgIAAIgEAAIgDABIgFAAIgCACIgEACIgIAAIgKAFIgEAAQgEAAgEACIAAABIABABQACACgCADIgDgDQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAAAAAAAQgDACgDADQAAAFAFABQAEAAAEgBIAOgFQABgBALAAIACABQAFgCAFAAIAEACQABAAAAABQABAAAAAAQABAAAAABQABAAAAAAQADgHAGABIAIAFIAIgBIAGABIARgDQADgBAEACIACgBIAGAAIAKgDQAGAAAEACQAAAAABAAQAAAAABAAQAAgBABAAQAAAAABgBQAGAAAJAGIAIAAIADgBIAEAAIACgCIAGABIAEADQAEAAAHgBIAKABIAOAAIAJADIACACQAAABAAAAQAAAAABAAQAAABABAAQAAAAABAAIAEgDQAHACAAACIACAEIACABQAHACADAGIABABQACADgBADIgCAGIAAADQgCAKgEAJQgEADgFACQACADgDAEIgEACIABACQgDAGgFACIgCABIgCAFIgDABIgCABIgFAAIgCABIgCAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIgDABIgCgDIACABIABgBQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBIgDgDIgHAAIgCAFQgBAEABACIACAAIACgCIABABIAAACIABABIADgBQgFgCAEgBIAHAFIAAABQgHABgFAFIgCAFIgGAGIgFACIAAABIAAAAIgCgBIgBABIAAABIACABQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABQgDADgEgDQgCACgDAAQgDgBgCgCIgCABIgBACIgFgDIAAAAIACAAIABgBIACACIAAAAIAAgBIAAgCIAAgBIgEADIgGgCIAAAFIgFgCIgCAAIgDAAIgCgCIgFAAIgFgDIgDAAIgEgDQgDgBgDACIgDAEQAAAAgBAAQAAgBgBAAQAAAAAAAAQgBAAAAAAIgCABIAAABIADAAQAAAEgDAGIAAADIgDALIAAAEIgEAFIgEABIgBAFIgEAAQgDADgCAAQgDgDgEAEQgFAEgCAAQgEgBgDgEIgBABQAAABgBAAQAAABAAAAQAAAAAAABQAAAAAAAAIgBAAIAAgCIgCgBQgBAAAAABQAAAAAAAAQgBAAAAABQAAAAABAAIABACQgEAAgFgCIgBgFIgBAAIgCAEIgHgDIgDgDIgEgBIgHgFQgDABgEgEQgDACgCgBIgFgDQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQgCgDgCgBIgFAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQgEADgFgBQgCgBgEgEQgEgDgEgBIgFAAIgEABIgHgDQgDACgCgBIgGgDIgFgBIgGgEIgIgBQgBgBAAgBQgBAAAAgBQgBAAAAAAQgBAAAAAAIgCAAIgDgCIgFAAQgKgDgHgFQgJgIgFgIQgCgFgFgFIgFgBQgFgEgFABQgBABgBALIgDAIIAAAHIgDAFIAAAEIgBAFQgBABAAABQAAAAAAABQAAABAAAAQAAABABAAIAFACIAGABIAGAAIAGACIACAEQAFAAAGAEIACACQAAAAABAAQAAABAAAAQABAAAAAAQABABABAAQADABAKgBIADAEIACADIgBAFQABACADACIACAEIADAEIAHAFIAHAEIAKAOIAFAEIACAHIAEAEIACADIAGACIACADIABADIAEABIAFAFIABAKQACAFAIAGIABADIABAFIADAEIAAADIADAFIACAAIABgBQACgDgEgFIABgEQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQACgDADgBIAJAEIAJAGQAEAEgCAGIgEAGQgBAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIAFgCQADgBADABIAEAFIAJAHIACAEIAIADQAGAGAFAJQABACAFABQAEAEACAEIgBACIAAADIABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQADABADAEIAEAHIACABIAFAEIAIABIAEAIIABAAIABABIABAEIADABIAAACQADgBAEAJIAEACIAAADIACAAIABABQACACAAAGIACACIADAFIADAGQABAEACABIAFgEIABgDIACAAIAAAAQgCAGAEAEQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgCAAQgDAFgDgCIgCAAQgDACAAADQAAAAABAAQAAABABAAQAAAAABAAQABAAABAAIABABQAAABAAAAQAAAAAAABQAAAAgBABQAAAAAAABIgBAAQgBgDgCgBIgDABIgBgBIgBgEQgEAAgDgDQABgFgEgDQAAAAAAgBQAAAAABgBQAAAAABAAQABAAABAAIAAgDIgCgBQAAgEgBgCIgBAAQgBACgEAAIgBABIgBAAIgBgEIACgCIgCgBIgBAAIAAADIgBAAQgHgFABgDQAEABADgBQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAAAAAAAIgFgBIgBgEIgBgCIgDABIgCgDIgBAAIAAADIAEAAQgCAEAFADIAAACIAAAAIgIgHQgGgGACgCIgGgGIgDgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIgDgCIgBgCQgKgGABgEIABgCIAAgBIgBABIgCAAIgDgDQgBAAAAAAQgBgBAAAAQgBAAAAABQAAAAAAAAIgFAEIAAAAIgCgDQgBgBAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIABABIABAAIAAAAIgBgCIgBABIgBgBIAAgDQgEgEgEgIIgDgCIgDgBIgDgDIgHgDIAAgBIACgBIAAgBIgBgCIgCAAQAAABgBAAQAAAAgBABQAAAAAAAAQAAABAAAAIgBAAIgDgEIgEgDIgDgBIgBgCIgEgEIgCAAQgGAHgGgDIADgGQADgDgBgEQgCgCgFgBIgHgDIgFgIIgEgDQgGgFgCgFQgBgHgEgDIgFACIgEgCQgDgJgEgBIgCAEQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBgBIgFgHQACgIgBgDQAAgCgGgFIgEgFIgGgEIgCgDQgFgBgEgCQgBgBgBgGQgCgGgCgCQgCgCgFgBIgIgEIgDgEIgIgBIgEgDIgLAAQgBgBgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgDAAIgDgCIgDAAQgDgEgDgBIgCABQgHAOgCAMIAAAGQgBABAAAAQAAABAAABQAAAAABABQAAAAAAAAQACACAEAAIAFAEIAJADIACACIAEACIAEAEIAEABIADAFIAMAIIAFAJIAGAFIABAFQAFAFABAHQAAAHgEAGIABACIAGAAQADgBADAEQADAHgBAJIgDAFIACAFIACAHIACAFQAAAAAAABQAAAAAAABQgBAAAAABQAAAAAAABIgCAEQgCACAAAEQgBAEgGAEQgGAEgBADIAAAFIgBACIAAAEIgDAHIgDACIgCAFIgEAFQgDACgGAAQgGgBgCACIgGAHIAAAEQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgEgCgBABIgDADIgCABQgCACAAAHIgHAHIgCACQgCADAAAGIgBACIAAADIgCAIIgDAPQgEAAgDgCgAFQEnIABAAIAAgDIgDgCIAAAAIAAgCIgBAAIgBADIAAADIADgBIABACgAAREZIAAAAIABAAIAAgBgAE9EEQgBAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAAgBIAAAAgAErD3IACAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAIgBAAgAETDmIAAAAIADACIACAAIABgCIgBAAIgBAAIAAABIgBAAIgBgCIgBAAgAgEDlQAAAAAAAAQAAABAAAAQAAAAABABQAAAAABAAIAAgBIAAgCIgCAAgAgBDhIABACIAAAAIAAgDIAAAAgAEPDhQAAAAABAAQAAAAAAAAQAAAAAAgBQABAAAAAAIgCAAgAEMDeIACgBIgCgBIgBAAgAAADVIAAAAIAAgBIAAgBIgCAAIACACgAAADNIAAgBIAAAAgAgJDGIAAADIABAAIAAgBIABAAIAAgBIgCgCgAAJDBIADAAIAAgBIgDAAgADkC0IABAAIAAgBIgBAAQAAAAgBAAQAAAAAAABQAAAAAAAAQABAAAAAAgAgCCnIABAAIAAgCIgBAAIgBAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAABAAgAgZCUIAAAAIAAAAIACgBIgBgBIgBAAIAAACgABkCQIABAAIAAAAIgBAAIAAAAgAAiBzIABAAIABAAIgBgBIAAgBIgBAAgABoA6QABAEAEABQAFgDAAgFQgBgDgEgBQgFADAAAEgAjsA1IgLACIgBACQABADADABIADgCIAFAAIAHgCIAAAAIAJAAQAEAAADgEQAAgGgKAAIgDACIgCAEIgDAAIgDAAIgCAAgAEUA2IABAGIABgBIgBAAIAAgGIgBAAgAkQAqQAAAAAAABQAAABABAAQAAABAAAAQABAAAAABIAAAFQACAEAFgCQAEgBACgDQAAAAAAAAQABgBAAAAQAAAAgBgBQAAAAAAAAIgEAAQgDgBgGgFIgBAAgADyAiQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABIACACIAEgBIABgCQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBgBAAAAIgEgCgAkPAhIAEAEQAEAAABgDQAAAAAAgBQAAgBAAAAQgBAAAAgBQAAAAAAgBIgEgBIgDACIgBAAgAj7AhQAHABABgHIgBgBIgBAAIgFACQgBAAgBAAQgBABAAAAQgBABAAAAQAAABAAAAIACABIgBAAgAExAaIABACIAAgBIAAgBIgBgBgAhvAXQAAAAABAAQABAAAAAAQABgBAAAAQAAgBABAAQAAgDgDgDIgDAAQgCAFAEADgAi9ASQADAEALgBQAKgBAAgGQgCgEgDAAIgIABQgFgEgEAAQgGAEAEAHgAETARIAAACIABACIAAgBIACgBIgBgCIgCAAgAjlALQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAABAAQABAGABABQAHACAGgEIAAgBQAAgBgGgCIgEgFIgBAAIgDACgAGEAUIgBAAIAFAAIAAgBIgEgBIAAACgAjIASIAAABIABABIACAAIAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAQgBAAAAAAgAlBAJIgBAIIADABQADgCADgEIAAAAIAEgCQAAgBAAAAQABAAAAgBQAAAAAAgBQAAgBAAAAIgBgFIgCAAQgDAFgHADgAiZAOIABACIACAAIABgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBgBAAIgBAAIgCACgADGADQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBADAFAEQAEAEACgBIAAgBQACgIgGgFIgBAAIgCACgAD1AHIAAABIACABIACgBIAAgBIgCgBIgBAAgACgAEIAAADQACADAEgCIABgBQAAgDgFgCgAiYgEIgEAEIAAAEQADAEAEgCIAEgEIAAgCQgBgEgEAAIgCAAgAiDgXIgDAEQAAAEAEAFQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQABAGADAEQAOACALgFIAAAAQAAgGgGgEQgEgCgDAEQgBADABADIgBABQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAIAAgEIgIgEIAAgCIAAAAIAKAAIABgDQgCgEgFgDIgCAAIgCgDIgDgCQAAAAgBABQAAAAAAABQgBAAAAABQAAABABAAgAEIgBQAAABAFAAIACADIAHABIACgDIAAAAIAAAAIAAAAIAAAAIgDgBIgEAAIgDgCIgFAAgAEoACIACACIAJgBIAAgCQAAAAABAAQAAAAABAAQAAgBAAAAQAAAAAAgBIgFgBQgJAAgBACIgBACIACAAIABAAgAEdADIABAAIAAABIABgBIgBAAIAAgBIgCAAgAjygHQgDAHAEADIABAAQACgDABgCQAAgFgEAAgAFTgEIgBABIABADIABAAIACgDIAEABIAAgBIgBgBIgCAAgAhcgGIABADIAEABIABgBIABAAIAAgBQgCgEgDAAgAGWgEIAAABIABAAIAAgBIABAAIgCgBgAGLgGIABABIAAAAIABAAIgBgCIAAAAgAFggIIAAACIABABIACgBIgBgDIgCAAgAD2gSQAAAGAFAAIAEAAIABABIADADQACACADgCQgBgFgEgEQgFgDgFAAIgCAAgADpgJQAAAAAAAAQABAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIgJgBIgEAAIgCgDIgKgCIgCABIAAADQAFADAFABIAGADQABAAAAAAQABAAAAAAQABAAABAAQAAAAABgBIAFACgAFwgMIAAACIABABIADAAIAAgDIgBAAgAFdgMIABACIABAAIAAgCIgBAAgAFggNIAAABIABAAQACgCgBgDIAAAAgAFFgQQAAAAAAABQAAAAABABQAAAAAAABQABAAABAAQAAABABAAQAAAAABAAQAAAAABgBQAAAAABAAQAAgBABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQgBgEgDAAQgCABgCADgAkIgQIAAABQAAAAABABQAAAAABABQAAAAABAAQAAAAABAAIAEgBIgBgBIAFAAIAAgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAAAQgCACgGAAgAFagNIABgFQAAgDgEgBIgCABQgBAEADADIABAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAgBgAmpgTQADAHAEgCIgBAAIACAAQAEgDgDgFIgBgDQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAIgBgCIgDgBQgDADAEAHgAikgPQACABAEgDIACACQAOgCgDgHIAAgBIgDAAQgHAFgHACIgCgBgAg+gSIAAABIABAAIAAgBIgBAAgAEjgSQADACADgBQAEgGgEgGIgCAAIgDACIgDADIAAAAQgBADADADgAEYgUIAAABIABACIABAAIAAgCIAAgBIgBAAIAAgBgAEzgZIAAABIAEADIADACIADABIAEgCIAFgCQAAAAAAAAQABgBAAAAQAAgBAAgBQgBAAAAgBQgGgEgFAAgAAwgVIAAABIAAAAIABAAIgBgBIAAAAgAFlgaQAAAAAAABQAAAAAAABQAAAAABABQAAAAABABQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIgCAAgAjKgZIAAAAQAAABAAAAQABAAAAABQABAAAAAAQABAAABgBIAAgBIgCgCIgBAAgAhcgYQAAAAABAAQAAgBABAAQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAIgFgCIgBACIAAAEIAAAAQABABAEABgAEagcIAAADIABAAIABgCIgCgCIAAABgAhSgeQAAABAAAAQAAABAAAAQABAAAAABQABAAAAAAIADgBIAAAAQAAgBgBAAQAAgBAAgBQAAAAAAAAQgBgBAAAAIgCAAgAFxgwIgCARQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAQAEABAEgDIADABIAAAAIADgDIAAgCQgHgFgBgCQgBgHgCgCIgDAAgAFmgdIABAAIABgBIgBgDIgBAAIAAgBIAAAFgAmwgeIABAAIAAgBIgBgBQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAABABgAmUgkQAAABAAAAQAAABAAAAQAAABAAAAQAAAAABAAQAAABAAAAQABAAAAAAQAAAAABAAQAAAAABgBIACgCQAAAAgBgBQAAgBAAAAQAAgBAAAAQgBAAAAgBIgCAAgADhg1QgGAEAEAFIAIAEIAGAAIAAABIAEADQABADAEABIAAgBQACgHgEgFIgCAAIgCABIgGgEQgDgGgFAAgAEYgjIACAAIAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAgAlngrQgDACAAAEIADACIAIgBIAKgBIAFAAIAEABIgBgBQABgEAHAAQAHAAABgDQAAAAABgBQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBgBQgBAAAAAAIgEABIgFAAIgFAFIgRACIgEgBIgDABgAFdgmQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAIACgCIgBgCIgBAAgAjhgkIABABIABAAIABgBIAAgBIgDAAgAmwglIABABQABAAABAAQABAAAAAAQABAAAAgBQAAAAABAAIAAgBIgEgBgAl6grQgBAAAAAAQAAAAgBABQAAAAAAAAQAAABAAAAIACADQAEABAEAAIACgCQgBgBAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgGgBgAD6grQgBADADACQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABgBIAEABIACgBIABgDQgDgDgDAAIgBAAQgEAAgCACgAGgg8QAAAAAAABQAAAAABABQAAAAAAABQABAAAAABIADADIgBAJQgBAGAFAAQAEgCAAgEQADABAEgEQAEgDgBgEIgCgBIgBgBIgDgEIgJgDIgEgIIgFgEIgCgDQgBgCgEgCQgFgCgDACIgDAEQgJgJgEgBIgCAEIgEADQAAAEACACQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABgBIAFAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAAAABIACADIADgBIAFAAQABAEAEAJIAAADQAAAAAAAAQAAABAAAAQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAQAAgBABAAQAAAAABgBIADgDgAi1g8QADABAFAFIAGACQADABAAADIgDADQAAABgBAAQAAAAAAABQgBABAAAAQAAABAAAAQACADAHgBQAHgBACgCIAAgBQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAgBgBAAIgEgCQAAgFACgEQAEgBAEgEQAEgFgDgEQgDgEgGAAIgEABIgEAAIgDAFIgEADIgJgDQgJACgFgBQgFgDgCABQgCABgCAGQgBACgFACQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQAEAFAEgEIACgDIAAgDIABAAIAEABIAFAAIAGgBIACAAgAEYguIADAEIAAACQAAABABAAQAAAAABAAQAAAAABAAQAAAAABgBIACgCIACgDIAFgEQABgCgCgEIgEgCQgCgGgGAAIgKACIAAABQgEACAAAFQAAAEACADQADAAADgCgAFAg1IABAFQADACAEAHIAFgDIgBgBIAAgBQABgEgDgDQgCgDgEgBgAmpgrQAAABAAAAQAAABAAAAQAAAAABAAQAAAAABAAIABgBQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAAAgADJgqIACABQADAAADgDIAFACQAEAAAAgEQABgEgCgCIgJAAIAAAAIgBAAQgHADABAHgAhsgvIAAABQAAAAAAABQAAABAAAAQAAABABAAQAAAAABABIABAAIACgCQAAgDgDgCgAnFgyQgEABABADIACADQACACAEgEQAEgDgCgEIgBAAIgGACgAE2g1QgBABAAAAQAAABAAAAQAAABAAAAQAAABABAAIADADIAEgEIgDgDIgDgBgACNg5QAAAFADADQADADAEgCIABAAQACgDgCgFQgDgFgDgBgAGFg8QAEAJAEACIABgBIAAAAQAAgJgEgIIAAgEQAAAAgBAAQAAAAgBgBQAAAAgBAAQgBAAgBAAQgEADAEAJgAmdg7QgBAEAAAEQAAAAAAAAQABABAAAAQAAAAABAAQAAAAABAAIAGgDIAEAAQAAAAABAAQAAAAABAAQAAAAABAAQAAgBABAAIABgDIgCgCIgFABIgEgCgACvg2QAGAAADADIABAAIABgFQgCgDgDgDIgDAAQgHADAEAFgAiOg3IACADQAGAAgCgGIgDgBQgBABgBAAQgBAAAAABQAAAAAAABQgBAAABABgAhgg3IABABIABAAIABgBIgBgDIgBAAQAAAAAAAAQgBAAAAABQAAAAAAABQAAAAAAABgAlzg+QgDAGAGACIACgDIABAAQAGAAAGgDIAAgBIgCgDIgHACIgEgCgAFrhNQgCAFgCAAIgGACIAAABQAGACAHAFIADAHIAEAAQABgHgDgGIgDgEIgBgEQgBAAAAgBQAAAAgBAAQAAgBgBAAQAAAAAAAAgAk6g6QACADADAAQABAAAAAAQABAAAAAAQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgCgCgDAAQgDACAAADgAD7g3IAAgBIgCgCIgBAAIAAACIgBAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAABAAgAm/g5IABAAIAAgBIgBAAgAlPg7IAAAAQAAABAAAAQAAAAABAAQAAAAABAAQAAAAABAAIABAAIAAgCIgBAAIgBgBgAlBg8IABABIACAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAIgBAAQAAAAgBAAQAAABAAAAQAAAAAAABQAAAAAAABgADRhCQgBAEADABQAEACACgCIAAgDQgBgCgGAAgAlghDIAAAEQABACAHABQAGAAACgBQAAgBABAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIgGgCIgBADIgBAAIgBgDIgFgCgAEEg8IACgBIABgEQgCgCgDgCIAAgBQACgEAHAAQACgBAEgDIAJAAQAHAAADgBIABgCIACABQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAABAAIgDgDIgGACIgKgBQgEACgEgBQgDAAgCgEQgDgDgDAAIgEABQgFAGgEgBIgFgCQgCABgCADQgDAEgCABQgGAAgDgFQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBgBAAQgCgCgIADIgBAAIgBACIAAABIAIABIACAIQABADADADQAFgCAGABIAHADQAAAAABAAQAAAAAAAAQABgBAAAAQABAAAAgBIADAAQAGAAAFAGgACohAIAAADIABABIACAAQAEgFgDgBIgBAAQAAAAgBAAQAAAAgBABQAAAAAAAAQgBABAAAAgAE9g+IAAgCIgNgEIAAAAQgDACABAEIADABIACgBQADADAHgDgAm/hUQABAHgDAHIgEAEQgCACABADQAAAAAAAAQABAAAAAAQABAAAAAAQABAAABAAQAGgDABgIQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAIAFgBIAAAAIAIgEIAAgEQAAgBgBAAQAAAAgBgBQAAAAgBAAQgBAAAAAAIgGAAIgCgBQgFABgBADgAj5g/IAAABIABAAIAAgBIAAAAgAkIhBQAAABAAAAQAAABABAAQAAAAABAAQAAABABAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAgBAAQAAgBAAAAIgCgCIgBAAIgBADgAHFhBIACACIABgBQABgDgBgDIgBgBIAAAAgAFKhCIACAAIAAgCIgBAAgAmChMIgBADQADAGAHgCIABgBIgDgHIgDAAgAFXhIQACADAEAAIABAAQABgDgBgEIgFgCIAAgBQgFADADAEgAE7hHIABABIABAAQAAAAABAAQAAAAABAAQAAgBAAAAQABgBAAgBIgBgCIgDAAQgBAAAAABQgBAAAAABQAAAAAAABQAAAAABABgAEihKQgBAAAAABQAAAAAAABQAAAAAAAAQABABABAAIAAABQADAAACgDQAAgBgBAAQAAgBAAAAQgBAAgBgBQAAAAgBAAIgCACgAG3hKQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAIACgBIgBgDIgBAAgADBhMIABACIAFAAIADACQAEgBgBgEIgFgEIgEAAQgDABAAAEgAHMhKIACgCIgDgBgAnEhRIAAACQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAIAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAgAgZhUIAAABIABAAIAAgBIgBgBgAgVhiQAAgDgCgDIgDgEIgEgHQgHgGAAgEIABgDIgEgSIgDgEIgCgIQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQgDAFAAADIACAFIAHARIAAAFIACADIABADIAFAFQACAFADADIAGAGIABACIABAAgAALhmIAAACIACACIACAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAAAAAgADNhrIAAABIABAAIAAgBIgBgBgABTiPQgEAFgCAEIAAADIAAAEIgDAEQAAABAAABQgBABABAAQAAABAAAAQABABABAAIACgBQACgGACgDIAAABIAGgGQAFgGAAgCQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAIgGABgAAbiIQABAEACAAIABAAIgBAAQAAgBAAAAQABAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAgAlAiFIACAAIgCgCgAAFiTQgEABABADQAAABAAAAQABABAAAAQABAAAAABQABAAABAAIADgDQADgBAFACIAAgBIAAgCQgBgDgEAAIgHABgAgKikIgFAIIACADIAGAAQACACgBAEQgBAFAAACQAFgBABgGIACgJQAFgBADAEQAEAAACgEIACgGIAEgCIACACIgCAIQgBADADAEQACAEADgBIAEgKIgBgFIgBgJIADgEIABgIIABABQACgHgGAAQgEALgEADIgEAAIgEAAIgFAGQgDAEgEAAIgDgFQgBgEgCAAQgDACgEAGgAAtibQAAADACADIACABIABgBQABgGgEgBgAAqisQgBAAAAAAQAAABAAAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAQAAgBAAAAIABAAIAAgCIgBgBIgCAAgABNizIACAAIADADQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIADAEQACACAEgBIAIgQIAIgQIAGgHIADgBIAFgJIAGgFIAGgJQAFgEACgDIgCgEIAAgFIgEgEIgCgFQgCgCgDAAIAAABIABAEIAAAEQgDAAgDgDQgDgDgDAAIgCABIAAADIgCACQgDACgEgEIgCgGQgHgGgIgCQgFAGgCAAIgEAAIgFACIgCAIQgBAFgCABIgCAAQgDAAgDADIgBAFIgBAFIgCACIgBADIgDADIgDAHIAAADIgEAJIgEANQgCAGADAGIAKACIADgCIAHgCIgBAAIACAAQAEAAAHADgAAGi2QgFAFAFAGQAFgBgDgKIgBAAIgBgBgAhFj9QgCADABACQABAEgBAEIgEADIgEADIAAAIIADADIABADIACACIACACIAGAIIADACQABACABAFIAHAGIAAAEQACAQAFgCQACgBACgDIAEgFIAEAAQAFgCADAAIAIADIAEAAIADABIADABQADgCAAgFIgBgLIgBgGIAAgGIgCgEIAAgDQgFgIgFgEQgBgBgEAAQgEAAgBgCQgCgCAAgDIgBgFQgCgBgCAFQgEABgEgDQgEgCgCAAQgEAGgGgEQgFgCAAgBIAAgDIgCgCIAAgEIgCAAgAhpjiQgCACABAEQAEAEAGgDIgBAAQAEgKgHgBIgFAEgAAwjkQAAAAAAABQAAAAABAAQAAABAAAAQABAAABAAIAEgDQAAgEgDgDIgBAAQgEADABAFgAA5jqIAAAAIABAAIAAgBIgBgBIAAACgACPjuIABAAIAAgBIgBAAgAgTkAQAAAIAEAHIAFABIABAAQABgFgDgGQgDgGgEAAgAgsj7IAAAEIABABIABgBQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBIgCAAIAAAAgAFiEtIAAABIABAAQAAgCAEgCIACgEIgDAAIgCgFIACgGIgCgCIgCAAQAAgDgCgFQAEAAADgEIAAAAIgFgEIAAgBIABgBQgBgCACgDIADgBIABgCIAFgBIAAgBQAGAAAFADQAGAEAAAFIgCADIAAAEIgCACIAAAIIgCACIgBAGIgEACIgBADIgDAAIAAAEQgBAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgEAAIgDACQgDgGADABgAGaEUQgJgIAAgNQAAgMAJgJQAIgJANAAQAMAAAJAJQAJAJAAAMQAAANgJAIQgJAJgMAAQgNAAgIgJgAGcDsQgIAIAAALQAAALAIAIQAIAIALgBQALAAAHgIQAIgHAAgLIAAAAQAAgLgIgIQgIgIgLAAQgLAAgHAIgAG5EPIgKgPIgIAAIAAAPIgEAAIAAggIAPAAQALAAAAAIQAAAJgKAAIAKAPgAGnD9IAHAAIAIAAQAEgBAAgEQAAgFgJAAIgKAAgAhxBwQAAgEADgEQAIACABAIQgBAEgDAAQgDAAgFgGgABUhsIAAgCIACAAIAAADgAhmhuIgFgDQgPgBgJgLIgBgHIgEgDIgCgFQgGgGgBgDQgDgLAEgJQABgCgCgEQgCgDABgDIADgDIAEAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQACgCgBgEIABgBIABAAQAIACgFAQIACAEIgCAIQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAIgFABQgCAFAEAEIADAAIADgEQADgDACABQAFACgBAJIgDANQAAADAEADQADADADgBIABAAIgBgFQgBgBAAAAQAAgBAAgBQAAAAAAAAQAAgBABAAQAEgCACABIAFADIACABIACAEQAGABAGgBQADgBACgDIAEgBIADgBIABgEQAGgJACABQAFADgGALQgGAMgFACIgIABQgDAEgGABIgCAAIgEgBgACPh9QgBgDACgDIAEgEIADgGIAMgLIABgHIAHgHIABgEIACgDIAIgFQAEgBADAFIACABQACACgBAGIAAAEIgFAGIgBAAQgCAEgCACIgHACIgFAGQgIADgCACIgDAGQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgFAEIgEABIgDgBgACtkCQAAgEAEgEQAEgFABgCQAHgWASgPQACgBAFgBIAHgEIAFgCQAGABABAGQgCAFgEACIgIADIgCADIgCAAQgIAHgDAGIgGAHIgBAEIgKAJQgGAIgGABgAifkLQgCgBgBgDIgCgGIgDgBIgDgBIgGgHIgKgFIgDAAQgBgBgBgBQAAAAgBgBQAAAAgBAAQAAAAAAAAIgGABIgBgCIgEABQgFgBgDAAIAAAAIABgBIgBgCIgBAAIgBABIAAABIABABIABAAIgBABIgCACIgFABIgCgBQgHgCgCgDIAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBQgBgEABgEIAFgBIAAgCIgBAAIAAgCIAIABIACADQACAAAEgEIAGAAQADABABADIABAAIAAgBIgCgCIAFgCIAFgEQANADAJAIIAEAHIAGACQADABABACIAGAGIADAEIAEABIABgBQACABAAAEIgCAGIgEACIgGAFIgFABIgDgBgAjikuIACACIgBgEgAjekuIAAABIABAAQAEgCAFABIgDgDIgHADgAi5kWIAEgDIACAAIADAEQAAADgDABQgGAAAAgFgADuk4QgCgFgCgCQgHgFAAgCQgCgGAEgFIAGgBQAFAAAFAHIADACIAGAFIAHAFIAAABIABAFQgBAAAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgBACIgDACQgJgBgIgEgAD/k7IAAAAIAAgCIAAAAg");
	mask.setTransform(72.345,67.875);

	// Color_1
	this.instance = new lib.Color_1("synched",0);
	this.instance.setTransform(150,150,1,1.0001,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleY:1},0).to({scaleY:1.0001,alpha:0},10).wait(10).to({startPosition:0},0).to({scaleY:1,alpha:1},10).wait(1));

	// Color_2
	this.instance_1 = new lib.Color_2("synched",0);
	this.instance_1.setTransform(150,150,1,1,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({scaleY:1.0001},0).to({alpha:0},10).wait(11));

	// Color_3
	this.instance_2 = new lib.Color_3("synched",0);
	this.instance_2.setTransform(150,150,1,1,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(40));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,149.3,134.9);


(lib.Logo_Container = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Logo_Stacked
	this.instance = new lib.Logo_Stacked("synched",0);
	this.instance.setTransform(21.05,-273.05,0.3256,0.3263,0,0,0,149.2,149.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(8).to({_off:false,startPosition:9},0).wait(31));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.5,-321.9,48.6,44);


(lib.Headline = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(1));

	// Text (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AKvGKQgRgOAAgVQAAgbAWgeQAUgaAsgmIAIhBQgZAlghAAIgBAAQgTAAgPgLQgSgPgDgbQgMARgPAPQgbAbgfAAQggAAgBhIQgQAdgXAaQgYAbgcAAQgjAAgPgUQgPgUAAgvIAAgBQgOAWgRATQglAogigBQgWAAgTgTQgTgSAAg5QAAgXAFgcQAGgcAPgUQAPgVAZAAQAKAAAMAGQALAFAAARQAAAdgPARQgOAOgSABIgBAhQAAAxAPAAQASAAAegaQAegaATgiIACgDIAHg4QALhGAWhuIADgEQAEgCAFAAQAIAAAMAGQAPAIAAAwQAAAegEAqIgPByQgGAnAAAYQAAAhAKAAQALABAcgiQAcghAOgeIAEgGQADgaAFgdQABgHAIgFQAIgGAKAAQASAAAAASIAAA2QAABOAHAAQAEAAAQgTIApgyQAHgbAQgRQAeghAvAAQANAAAMAGQAEgZACgDQAHgIAKAAQANAAAHAJQAJAKAAARIgCBAQgDAwgFArQA+g4AVgrQAFgwAGgoQAJhIAMgiQAAgGAGgFQAGgEAIAAQAWAAAAAWIgEBNQgDBAgFA7QATgZAVAAQAhAAAMARQANARAAAaIgEAuQAAAFACAAQAPAAAUgVQATgUATgdIATgdIAGhqQgqgDgQgJQgFgDgBgEIgBgEIADgJQADgHABAAIADgBIA6ALQAHhiAJAAQAMgFAKAAQAdAAAAApQAAAKgDATIgFAlIAygDIAOgBQALAAAAAJQAAALgFAAQgaAIgvABQgEA2gCB2IgCBhQgCASgKANQgKAMgNAAQgLAAgIgJQgGgGAAhGIABg9QgNAWgTAUQgYAZggAAQg6AAAAhCIACgmQAAgFgCAAQgJAAgNAQQgNARgKAUQgKBagNAHQgUARgMAAQgNAAAAgZQAAgdAGhHQgJAOgKANQgaAfgnAeQgLBQgUA0QgTA0geAAQgfAAgUgRgALHFoQAAAJACACQADADAHAAQAMAAAPhcQgnAkAAAqgALLBaQgPAhABAaQAAAZAPAAQAFAAAJgSQAKgUAFgVQAHgYAAgQQAAgRgIAAIgCAAQgNAAgOAggAESAhQgEAKAAANIgBANQAVgFAAgeQAAgJgFAAQgIAAgDAIgAufFnQAAAFgFgOQgEgPgFgsQgFgtgChbIgJh1QAAgIAIgHQAHgGAJAAQAZAAANAnQAQgZAXAAQA+AAAABEQAAAvgTAcQAZgTATgYQAUgZAMgWIAFgIQAIgWASgSQAdgdAdAAQAGAAACACIADAAQAMAAALANQANARAAAcIABBJQAAASADAAQAPAAAshHIAMgVQgNgSgFgLQgIgQAAgQQAAgJAEgOQAEgOAKAAIAKgCQAPgDAHAAQAaAAAAAfQAAAkgMAfQAcAtAAAlQAAAbgGAUQgFATgKAVQgHAPAAAGQAAAMAGAMIABAFQAAAHgFAFQgCADgEACIgIABQgNAAgMgPQgLgOAAgoQAAgSAYgsQARgjAAgIQAAgOgJgQIgBAAIgGgFIgFAKQgWAogZAhQgZAggWAAQgWAAgMgaQgNgbAAgwQgLAhgQAUQgPAUgNAAQgOAAgGgHQgGgHgCgSQgTAcgXAOQgtAcgqAAIgLAAIgDAAIABANQAIAxAAAuQAAAOgCAGQgCAKgJAHQgKAIgLAAQgMAAgHgIgAt6BZIAGBZQAYgQAJgVQAHgSAAgjQAAgTgEgHQgDgFgIAAQgSAAgNAggAqdAtQgnAiAAArQAAAOAEAAQAFAAALgUQALgTAKgZIANgjIAAgEIAAAAQgCAAgNAMgAn/AJQAAAIAFALIACgaQAAgLgEAAQgDAAAAASgAgkC8QgJglAAgdIAAgCQAAitALg0QgIgGAAgJQAAgDACgEIAQgCQAFgGAJAAQAKAAAIAEQBGAAA3AeQA1AeAABQQAABUgYAvQgZAugiAQQghAQgkAAIgNAAQgHAGgOAAQgcAAgIgkgAAlgoIABCsQAAAigCAQQAhgFAQgXQAQgWAFgeQAFgZAAgrQAAgygQgkQgQglgpAAIgGAAQAEAVABAcgAx2DMQgNgMAAgPQAAgQAPAAQAJAAAFAMQAFAOAMAAQANAAAFgHQAFgHAAgRQAAgOgWgrQgSgjgGgSQgJgYAAgVQAAg0ASgdQASgdAYgLQAYgLATAAQAUAAAMANQAJAJAAAIQAAAFgEAFQgEAGgHAAQgDAAgGgHQgJgKgJAAQgNAAgLAMQgKANAAAhQAAAZAFATQAHAcAXAmQANAUAHARQAGAPAAAUQAAAmgZAVQgYAVgrAAQgXAAgPgOgAlGC+QgRgUgQgdIgFgJQgaBLgPAAQgVAAAAgqQAAgyAliIIAFgPQAEgRAMgJQALgJANAAQAcAAAAAfQAAAGgJAhIgTBIQAVgcAagaQAZgYAKAAQAEAAAFADQAHAEAAAGQAAAGggAhQgfAfghAcQAPALARAcQAKAQAHAGQAIAHAKAAQAWAAATgRQAUgRANgTIANgXQAKgQAFAAIAEACQADADAAAHIgDAQQAAAEgOAbQgOAZgaAXQgZAWglAAQgYAAgRgTgAImgVQgBgGAQgLQAQgLAIAAQAJAAAAAMQAAALgIAKQgJALgIAAQgXAAAAgQg");
	mask.setTransform(130.025,41.075);

	// Color_1
	this.instance = new lib.Color_1("synched",0);
	this.instance.setTransform(150,150,1,1.0001,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleY:1},0).to({scaleY:1.0001,alpha:0},10).wait(10).to({startPosition:0},0).to({scaleY:1,alpha:1},10).wait(1));

	// Color_2
	this.instance_1 = new lib.Color_2("synched",0);
	this.instance_1.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).wait(10).to({scaleY:1.0001},0).to({alpha:0},10).wait(11));

	// Color_3
	this.instance_2 = new lib.Color_3("synched",0);
	this.instance_2.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(21));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(14.5,25.1,245.60000000000002,57.1);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(1));

	// Text
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AANAiIAAgkQAAgMgEgDQgCgCgGgBQgGAAgDAEQgEAEAAAOIAAAgIgQAAIAAhCIAQAAIAAAHQAHgIAKAAQANAAAHAJQAEAFAAAOIAAAng");
	this.shape.setTransform(152.825,18);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZAZQgKgJAAgQQAAgOAKgKQALgKAOAAQAPAAALAKQAKAKAAAOQAAAQgKAJQgLALgPAAQgOAAgLgLgAgNgPQgGAFAAAKQAAAKAFAFQAGAHAIgBQAJABAFgHQAGgFAAgKQAAgKgHgFQgFgGgIAAQgHAAgGAGg");
	this.shape_1.setTransform(144.75,18.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHA1IAAhDIAPAAIAABDgAgGgiQgDgDAAgEQAAgFADgDQADgDADAAQAEAAADADQADADAAAFQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape_2.setTransform(138.725,16.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAuIAAg0IgHAAIAAgPIAHAAIAAgYIAOAAIAAAYIAMAAIAAAPIgMAAIAAA0g");
	this.shape_3.setTransform(135.2,16.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZAYQgIgJAAgPQAAgPAJgKQAKgJANAAQAMAAAHAJIAAgIIAQAAIAABCIgQAAIAAgGQgHAIgMABQgPAAgJgMgAgMgOQgFAGAAAIQAAAJAFAGQAFAGAHAAQAIAAAGgFQAFgGAAgKQAAgJgFgGQgGgFgIgBQgHABgFAGg");
	this.shape_4.setTransform(128.725,18.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVAiIAAhCIAPAAIAAAHQADgFADgBQAEgCAGAAQAGAAAGACIgGAPQgEgDgFAAQgFAAgDAEQgFAFAAAKIAAAig");
	this.shape_5.setTransform(122.55,18);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgHA1IAAhDIAPAAIAABDgAgGgiQgDgDAAgEQAAgFADgDQADgDADAAQAEAAADADQADADAAAFQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape_6.setTransform(117.575,16.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghA1IAAhnIAPAAIAAAHQAIgJALAAQAOAAAJAKQAKAJAAAQQAAAQgKAKQgKAJgMAAQgMAAgIgKIAAAtgAgNggQgGAGAAAKQAAAKAGAGQAFAEAIAAQAIAAAFgFQAFgGAAgJQAAgJgFgGQgFgHgIAAQgIAAgFAGg");
	this.shape_7.setTransform(111.775,19.825);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgPAfQgGgFgCgHIANgGIADAHQADACAEAAQADAAADgCQACgDAAgDQAAgDgCgCIgGgEIgGgCQgGgDgDgDQgEgEAAgHQAAgJAFgFQAGgHAJABQAIgBAFAEQAFADADAFIgMAIQgDgGgHAAQgCAAgBACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAABQABAAABAAIADADIAIAEQAIAEACABQAFAFAAAIQAAAJgGAGQgHAIgLAAQgJAAgGgFg");
	this.shape_8.setTransform(104.55,18.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AANAiIAAgkQAAgMgEgDQgCgCgGgBQgGAAgDAEQgEAEAAAOIAAAgIgQAAIAAhCIAQAAIAAAHQAHgIAKAAQANAAAHAJQAEAFAAAOIAAAng");
	this.shape_9.setTransform(97.725,18);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgHA1IAAhDIAPAAIAABDgAgGgiQgDgDAAgEQAAgFADgDQADgDADAAQAEAAADADQADADAAAFQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape_10.setTransform(92.075,16.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVAiIAAhCIAQAAIAAAHQADgFACgBQAEgCAGAAQAGAAAGACIgHAPQgDgDgFAAQgFAAgDAEQgFAFABAKIAAAig");
	this.shape_11.setTransform(84.5,18);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVAbQgHgIAAgPIAAgmIAQAAIAAAmQAAAIADAEQADAFAGAAQAHAAADgFQADgEAAgIIAAgmIAQAAIAAAmQAAAPgHAIQgJAIgNAAQgNAAgIgIg");
	this.shape_12.setTransform(77.475,18.175);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYAZQgLgJAAgQQAAgOALgKQAKgKAOAAQAQAAAJAKQALAKAAAOQAAAQgLAJQgKALgPAAQgOAAgKgLgAgNgPQgGAFAAAKQAAAKAFAFQAFAHAJgBQAJABAFgHQAGgFAAgKQAAgKgHgFQgFgGgIAAQgIAAgFAGg");
	this.shape_13.setTransform(69.4,18.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggA0IAZgvIgeg4IAUAAIASAnIATgnIASAAIg1Bng");
	this.shape_14.setTransform(61.3,19.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgZAwQgIgKAAgOQAAgQAJgJQAKgKANAAQAMAAAHAKIAAg5IAQAAIAABzIgQAAIAAgHQgHAJgMAAQgPAAgJgLgAgMAJQgFAGAAAJQAAAJAFAGQAFAGAHAAQAIAAAGgFQAFgGAAgKQAAgKgFgGQgGgGgIAAQgHAAgFAHg");
	this.shape_15.setTransform(49.375,15.725);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AANAiIAAgkQAAgMgEgDQgCgCgGgBQgGAAgDAEQgEAEAAAOIAAAgIgQAAIAAhCIAQAAIAAAHQAHgIAKAAQANAAAHAJQAEAFAAAOIAAAng");
	this.shape_16.setTransform(41.425,18);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgHA1IAAhDIAPAAIAABDgAgGgiQgDgDAAgEQAAgFADgDQADgDADAAQAEAAADADQADADAAAFQAAAEgDADQgDADgEAAQgDAAgDgDg");
	this.shape_17.setTransform(35.775,16.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgaA1IAAhpIA1AAIAAAPIglAAIAAAbIAjAAIAAAOIgjAAIAAAxg");
	this.shape_18.setTransform(30.775,16.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(40));

	// Button (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AuVCgIA2igIg2ifIcrAAIg2CfIA2Cgg");
	mask.setTransform(91.825,16);

	// Color_1
	this.instance = new lib.Color_1("synched",0);
	this.instance.setTransform(150,150,1,1.0001,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleY:1},0).to({scaleY:1.0001,alpha:0},10).wait(10).to({startPosition:0},0).to({scaleY:1,alpha:1},10).wait(1));

	// Color_2
	this.instance_1 = new lib.Color_2("synched",0);
	this.instance_1.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).wait(10).to({scaleY:1.0001},0).to({alpha:0},10).wait(11));

	// Color_3
	this.instance_2 = new lib.Color_3("synched",0);
	this.instance_2.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(21));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,183.7,32);


(lib.Callout_Title = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(1));

	// Callout (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AigDFIAAgxQgggEgZgRIAAAAQgUgNgNgUIAAAAIAigjQAMASANAJIAAAAQARANAYAAIAAAAQAWAAAMgMIAAAAQAMgLAAgRIAAAAQAAgNgLgMIAAAAQgFgGgbgLIAAAAQgogQgUgSIAAAAQgVgTAAghIAAAAQAAggAUgXIAAAAQAUgVAcgGIAAAAIAAgtIAlAAIAAAtQASABATAJIAAAAQASAKAMAOIAAAAIgdAmQgUgZgcABIAAAAQgUgBgKALIAAAAQgJAJAAAMIAAAAQAAANAMAIIAAAAQAGAFAfAOIAAAAQAqATAMALIAAAAQAXAWAAAhIAAAAQAAApgbAbIAAAAQgUATgeAGIAAAAIAAAzgAGXBuQgsgsAAhEIAAAAQAAhEAsgsIAAAAQAtgtBHAAIAAAAQBGAAAtAtIAAAAQAtAsAABEIAAAAQAABEgtAsIAAAAQgtAshGAAIAAAAQhHAAgtgsgAHDhMQgcAdAAAtIAAAAQAAAtAcAdIAAAAQAcAdAsAAIAAAAQAsAAAcgdIAAAAQAcgdAAgtIAAAAQAAgtgcgdIAAAAQgcgegsAAIAAAAQgsAAgcAegAAfCNQgTgJgRgQIAAAAIATgzQANASASAJIAAAAQAUAMAXAAIAAAAQAdAAARgSIAAAAQAQgRAAgbIAAAAQAAgagRgQIAAAAQgSgOgdABIAAAAQghAAggASIAAAAIAkidICKAAIAAAyIhkAAIgLAwIAVgCQAwAAAdAeIAAAAQAbAaAAAtIAAAAQAAAwgfAeIAAAAQgeAfg0AAIAAAAQgnAAgagNgAvzBxQgtgrAAhHIAAAAQAAhEAsgrIAAAAQAtgvBJAAIAAAAQAoAAAeAQIAAAAQAiASAWAlIAAAAIgzAcQgMgYgXgMIAAAAQgTgKgXAAIAAAAQgqAAgbAbIAAAAQgfAdAAAyIAAAAQAAAvAeAdIAAAAQAaAZApAAIAAAAQAjAAAYgSIAAAAQAVgRAHgdIAAAAIhNAAIAAgxICJAAIAAADQAABQgsArIAAAAQgnAohEAAIAAAAQhEAAgogpgAqtB+QgfgdAAgvIAAAAQAAgvAegdIAAAAQAcgbAtAAIAAAAQAyAAAaAgIAAAAQAXAbAAAxIAAAAIAAAEIiRAAQAAAUAJANIAAAAQANASAaAAIAAAAQAfAAAPgZIAAAAIAyAIQgZA9hHAAIAAAAQguAAgcgcgAo1AYQgEgTgOgJIAAAAQgMgKgRAAIAAAAQgQAAgMAKIAAAAQgOAJgEATIAAAAIBdAAIAAAAgAPkCPQgKgKAAgPIAAAAQAAgPAKgKIAAAAQAKgKAPAAIAAAAQAPAAAKAKIAAAAQALAKAAAPIAAAAQAAAPgLAKIAAAAQgKAKgPAAIAAAAQgPAAgKgKgANdCUIAAiUIgVAAIAAgvIAVAAIAAg1QAAgwAZgVIAAAAQAUgQAdAAIAAAAQARAAAOAHIAAAAIAAAxQgLgIgOAAIAAAAQgNAAgHAKIAAAAQgFAKAAAYIAAAAIAAAuIAyAAIAAAvIgyAAIAACUgALaCUIAAiUIgVAAIAAgvIAVAAIAAg1QAAgwAZgVIAAAAQAUgQAdAAIAAAAQARAAAOAHIAAAAIAAAxQgLgIgOAAIAAAAQgNAAgHAKIAAAAQgFAKAAAYIAAAAIAAAuIAyAAIAAAvIgyAAIAACUgAnYCUIAAiUIgVAAIAAgvIAVAAIAAhCIA3AAIAABCIAmAAIAAAvIgmAAIAACUgAPiA4IAAjQIA3AAIAADQg");
	mask.setTransform(-0.0752,6.0003);

	// Color_1
	this.instance = new lib.Color_1("synched",0);
	this.instance.setTransform(0,93.2,1,1.0001,0,0,0,150,150);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleY:1},0).to({scaleY:1.0001,alpha:0},10).wait(10).to({startPosition:0},0).to({scaleY:1,alpha:1},10).wait(1));

	// Color_2
	this.instance_1 = new lib.Color_2("synched",0);
	this.instance_1.setTransform(0,93.2,1,1,0,0,0,150,150);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).wait(10).to({scaleY:1.0001},0).to({alpha:0},10).wait(11));

	// Color_3
	this.instance_2 = new lib.Color_3("synched",0);
	this.instance_2.setTransform(0,93.2,1,1,0,0,0,150,150);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).wait(21));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115.7,-25.4,231.4,61.699999999999996);


(lib.Headline_Container = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Headline
	this.instance = new lib.Headline("synched",19);
	this.instance.setTransform(133.2,-373.6,0.52,0.52,0,0,0,136.2,38.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({_off:false},0).wait(21));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(67.1,-393.2,141.70000000000002,63.80000000000001);


(lib.CTA_Container = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// CTA
	this.instance = new lib.CTA("synched",9);
	this.instance.setTransform(200.7,-508.4,0.5405,0.5374,0,0,0,74.8,15.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).wait(31));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(160.3,-516.6,99.19999999999999,17.200000000000045);


(lib.Callout_Title_Container = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Callout_Title
	this.instance = new lib.Callout_Title("synched",9);
	this.instance.setTransform(148.4,17.7,0.6028,0.6009,0,0,0,1.6,2.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).wait(10).to({startPosition:19},0).to({_off:true},1).wait(20));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(77.7,1.1,139.5,37.1);


// stage content:
(lib._468x60 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,34,239];
	// timeline functions:
	this.frame_0 = function() {
		this.loops = 0;
	}
	this.frame_34 = function() {
		if (this.loops >= 3) {
			this.stop();
		} else {
			this.loops++;
		}
	}
	this.frame_239 = function() {
		this.gotoAndPlay(34);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(34).call(this.frame_34).wait(205).call(this.frame_239).wait(1));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgkjgExMBJHAAAIAAJjMhJHAAAg");
	this.shape.setTransform(234,29.9883,1,0.9804);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(240));

	// Logo
	this.instance = new lib.Logo_Container("single",0);
	this.instance.setTransform(154.5,377.9,1,1,0,0,0,116.8,17.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).to({y:347.9,alpha:1},10,cjs.Ease.quadOut).wait(65).to({mode:"synched",startPosition:9,loop:false},0).wait(10).to({mode:"single",startPosition:19},0).wait(60).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:29},0).wait(50).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:39},0).wait(16));

	// Headline
	this.instance_1 = new lib.Headline_Container("single",19);
	this.instance_1.setTransform(149.95,464.55,1,1,0,0,0,136.2,38.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(94).to({_off:false},0).to({y:434.55,alpha:1},10,cjs.Ease.quadOut).wait(50).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:29},0).wait(50).to({mode:"synched",loop:false},0).to({alpha:0,mode:"single",startPosition:39},10).wait(16));

	// Callout_Title
	this.instance_2 = new lib.Callout_Title_Container("single",9);
	this.instance_2.setTransform(110,42.2,1,1,0,0,0,110,12.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(14).to({_off:false},0).to({y:12.2,alpha:1},10,cjs.Ease.quadOut).wait(60).to({mode:"synched",loop:false},0).to({alpha:0,mode:"single",startPosition:19},10).wait(130).to({y:22.2,startPosition:9},0).to({y:12.2,alpha:1},10,cjs.Ease.quadOut).wait(6));

	// Callout_Body
	this.instance_3 = new lib.Callout_Body();
	this.instance_3.setTransform(150.25,240.45);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(19).to({_off:false},0).to({y:210.45,alpha:1},10,cjs.Ease.quadOut).wait(55).to({alpha:0},10,cjs.Ease.quadOut).wait(135).to({y:220.45},0).to({y:210.45,alpha:1},10,cjs.Ease.quadOut).wait(1));

	// CTA
	this.instance_4 = new lib.CTA_Container("single",9);
	this.instance_4.setTransform(150,584,1,1,0,0,0,74,16);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(24).to({_off:false},0).to({y:554,alpha:1},10,cjs.Ease.quadOut).wait(50).to({mode:"synched"},0).wait(10).to({mode:"single",startPosition:19},0).wait(60).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:29},0).wait(50).to({mode:"synched",loop:false},0).wait(10).to({mode:"single",startPosition:39},0).wait(16));

	// image1
	this.instance_5 = new lib.image1();
	this.instance_5.setTransform(233.6,55.25,1,1,0,0,0,75,58.7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(9).to({_off:false},0).to({alpha:1},10).wait(65).to({alpha:0},10).wait(120).to({alpha:1},10).wait(16));

	// Image_2
	this.instance_6 = new lib.Image_2();
	this.instance_6.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(84).to({_off:false},0).to({alpha:1},10).wait(59).to({alpha:0},10).wait(77));

	// Image_3
	this.instance_7 = new lib.Image_3();
	this.instance_7.setTransform(150,150,1,1,0,0,0,150,150);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(153).to({_off:false},0).to({alpha:1},10).wait(51).to({alpha:0},10).wait(16));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(62.2,-0.4,429.2,140.5);
// library properties:
lib.properties = {
	id: '95242D917D7A6840BAAA821D45A31829',
	width: 468,
	height: 60,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/img_1.jpg", id:"img_1"},
		{src:"images/img_2.jpg", id:"img_2"},
		{src:"images/img_3.jpg", id:"img_3"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['95242D917D7A6840BAAA821D45A31829'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;